### ISSUE TITLE
Collections overwritten when there is an invalid auth config and sync_mode: sync

### ISSUE THREAD

**Issue by mza921** [mza921/Plex-Auto-Collections#102]
How to reproduce the issue (tested with a Trakt list):
1. Start with a populated collection with `sync_mode: sync`
2. Wipe out the Trakt authorization information in the config file
3. Run the script with the `--update` option, which skips the Trakt authorization and config update process

The script will continue to update the collection and remove all items. The expected behavior is to cancel the update, so that the collection is preserved for when authorization is actually valid.

**Comment by meisnate12** [comment]
so if the collection needs any of the different apis and its invalid we should cancel the update on the whole collection?

**Comment by mza921** [comment]
I haven't tested what happens if there are multiple apis for a collection. But with a single api, if `sync_mode: sync`, then it should cancel the update. Otherwise, all the collection items get removed.

**Comment by meisnate12** [comment]
right now it doesnt im asking should it

**Comment by meisnate12** [comment]
I've been thinking about this. The best way to handle this in my opinion is that if any part of the config of a collection fails it automatically switches to append so it won't remove any movies

**Comment by mza921** [comment]
Good idea

**Comment by meisnate12** [comment]
ok ill work on this for my next release

**Comment by meisnate12** [comment]
this can be closed
