### ISSUE TITLE
Identify problem items with IMDB List/New Movie Agent/Caching.

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#105]
I'm still getting crashes out of IMDB lists during caching (New Movie Agent), but I believe it's a metadata issue with some of my media.
My question is, how can I locate/identify what item is causing the crash? The items don't appear to be processing in a discernible order, and the output is a bit unclear. If I can figure this out, I think I can work through and fix what's causing the problem.

In the example below, is the problem with "The Christmas Aunt" or some movie ending in "r of Magic" ??
I've re-matched and refreshed "The Christmas Aunt" but problems persist. "r of Magic" is more difficult to locate on my Plex...

Example:
```
| Updating collection: IMDb Top 250...
| Sync Mode: sync
|
| Processing imdb_list: https://www.imdb.com/search/title/?groups=top_250
| 250 Movies found on IMDb
| Cache | + | plex://movie/5f677cb36d8478003905a510 | None | 742159 | 9/11: The Final Minutes of Flight 93
| Cache | + | plex://movie/5e35ecaa0e383b003d5a361b | None | 667536 | The 41st Day
| Cache | + | plex://movie/5ecc3bed308fd9003a645535 | None | 707890 | AEW Double or Nothing 2020: The Buy-In
| Cache | + | plex://movie/5f437920be690b00433cbc67 | None | 735933 | African Kung-Fu Nazis
| Cache | + | plex://movie/5d7770176afb3d0020612d35 | None | 145706 | Al Murray, The Pub Landlord - The Only Way is Epic
| Cache | + | plex://movie/5d7768317e9a3c0020c6bfd3 | None | None | Alice
| Cache | + | plex://movie/5d9f3e096fc551001ef8c1bd | None | 203610 | Alicia Keys - VH1 Storytellers
| Cache | + | plex://movie/5d7770207a53e9001e79bf87 | None | 85905 | Amy Winehouse - A Last Goodbye
| Cache | + | plex://movie/5d776feef617c9002019b187 | None | 279223 | Angelina Ballerina - Musical Moves
| Cache | + | plex://movie/5ec75f85e515a5003f695891 | None | 706478 | Apocalypse Now Redux
| Cache | + | plex://movie/5e35ecb5dcd15c003c805518 | None | 668378 | ATS with Kobe Bryant
| Cache | + | plex://movie/5ecc3b9b7da90e003888f1ff | None | 706973 | The Band
| Cache | + | plex://movie/5eb8f228422c5200454a3048 | None | 693570 | Big Wata
| Cache | + | plex://movie/5d77705196b655001fe935d0 | None | 509356 | Birth Of The Solar System
| Cache | + | plex://movie/5d776f9cad5437001f813b35 | None | 381115 | Bob the Builder: Building Sky High
| Cache | + | plex://movie/5d776860103a2d001f56f85a | None | None | Body Parts
| Cache | + | plex://movie/5d776830880197001ec927d3 | None | None | Bolero
| Cache | + | plex://movie/5f96f2cfb5637a002d3c153a | None | 757183 | The Campaigns That Made History
| Cache | + | plex://movie/5d776fdf594b2b001e7426c6 | None | 302442 | Cast Alaska
| Cache | + | plex://movie/5f68ce3e30852a00414365ef | None | 744929 | The Christmas Aunt
Traceback (most recent call last):r of Magic
  File "app/plex_auto_collections.py", line 830, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "app/plex_auto_collections.py", line 461, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 154, in add_to_collection
    movies, missing = imdb_tools.imdb_get_movies(config_path, plex, value)
  File "/opt/scripts/Plex-Auto-Collections/app/imdb_tools.py", line 98, in imdb_get_movies
    imdb_id = tmdbapi.imdb_id
AttributeError: 'AsObj' object has no attribute 'imdb_id'
```

**Comment by meisnate12** [comment]
whats the next movie in you library alphabetically after The Christmas Aunt?

**Comment by meisnate12** [comment]
ok so i think I've figured out whats wrong I'm not sure exactly what movie it is because the `r of Magic` line overwrites itself so the problem is with whatever movie ends with `r of Magic` if you run it again and watch it it will go in alphabetical order so you should be able to tell at least close to where the movie is

**Comment by bigdork** [comment]
"Christmas Belle" is the next item, alphabetically, but I think I found the movie that was causing that exact problem - "The Colour of Magic" -- It's a TV series in IMDB, and the radarr item links to a TV series in TMDB also (https://www.themoviedb.org/tv/5885-the-colour-of-magic).  2 episodes, released as one movie. 

I fixed that one (moved over to TV) and the script proceeds past that point, now crashing similarly on another item "us Island" ...

The next item in the library, alphabetically, is "My Hero Academia: Heroes Rising" which is on both TMDB and IMDB as a movie, has been re-matched and refreshed, but still crashes here.

```
| Cache | + | plex://movie/5d7768535af944001f1ff726 | None | None | Mother
| Cache | + | plex://movie/5d7770d7594b2b001e752bb8 | None | 596592 | Motown 60: A Grammy Celebration
| Cache | + | plex://movie/5f461beed6c4190040d728f8 | None | 736507 | My Hero Academia Make It! Do-or-Die Survival Training
Traceback (most recent call last):us Island
  File "app/plex_auto_collections.py", line 830, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "app/plex_auto_collections.py", line 461, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 154, in add_to_collection
    movies, missing = imdb_tools.imdb_get_movies(config_path, plex, value)
  File "/opt/scripts/Plex-Auto-Collections/app/imdb_tools.py", line 98, in imdb_get_movies
    imdb_id = tmdbapi.imdb_id
AttributeError: 'AsObj' object has no attribute 'imdb_id'
```

**Comment by meisnate12** [comment]
if you run it again and watch it it will go through your whole library in alphabetical order so you should be able to tell at least close to where the movie is

**Comment by bigdork** [comment]
I suspect I'm going to find a bunch of these, just looking for some guidance on locating which movie the problem child is.

**Comment by bigdork** [comment]
@meisnate12  I suspect I'm going to find a bunch of these, just mostly looking for some guidance on locating which movie the problem child is. As you can see in the output I've posted, it appears to jump large chunks groups of items (there's probably 100 movies between "Motown" and "My Hero", so "next movie alphabetically" doesn't really work. 

I watched, but I don't see an output of what item it is currently processing when it crashes. All I can really tell is it probably starts with an M or N, comes after "My Hero," and ends in "us Island"

**Comment by meisnate12** [comment]
sometimes when i run it i have to hit the arrow keys while its looking though the library to get the line update to show

**Comment by bigdork** [comment]
I tried the arrow thing, but no love.

Currently at 24964 movies in the library, so I expect some issues. Have been super pleased with the work you guys are doing. Really helpful to manage this monster. Maybe this is a "me" issue because of the library size...

**Comment by bigdork** [comment]
Found this one.
"Mysterious Island" - a TV Movie that seems to have been removed from TMDB, but Radarr still has it's link as https://www.themoviedb.org/movie/524655-mysterious-island.

It is on IMDB, https://www.imdb.com/title/tt0448965/

This got added from my Radarr "Actor Patrick Stewart" import list. Don't think it'll ever get watched, so I'll just delete it and move on. But you can see there's quite an alphabetical jump from "My Hero" to "Mystery" especially since there's 3 other "My Hero Academia" movies after the last one listed in the output.

Maybe there's some additional error handling or crash output you could add? 
But as-is, with the 3 bits of info (probably starts with X, comes after Y, and ends in Z) I can work through these.

**Comment by meisnate12** [comment]
ultimately we would just catch this error and set its IMDB ID to NONE so you won't see this error after my next update the tool isnt really designed to check your library for weird things like this. The script should just keep on moving on.

**Comment by bigdork** [comment]
Yeah, seems like a "me" issue - I have enough to help identify the weirdness and fix them. Thanks for talking through with me.

**Comment by meisnate12** [comment]
no problem
