### ISSUE TITLE
Enhancement: Collections based on other collections?

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#107]
Considering the extended time it takes to run trakt and imdb lists, is it possible to create collections based on a pre-existing collection?

For example:
```
  All Christmas:
    trakt_list:
      - https://trakt.tv/users/movistapp/lists/christmas-movies
      - https://trakt.tv/users/2borno2b/lists/christmas-movies-extravanganza
  Kids Christmas:
     plex_search:
       collection_name: Christmas
     filters:
       genre: [Family, Children]
       content_rating: [G, E, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV]
```
Two currently-working solutions would be to create the Kids collection with the same trakt lists and add filters, or create the first Christmas collection as described, mass-edit every film via Plex to add a "Christmas" genre, then create a Kids Christmas collection based on that `genre:` 

Re-running the same trakt lists seems pretty inefficient, and the second solution requires manual intervention.

**Comment by meisnate12** [comment]
im sure this wouldn't be hard to add but i wouldn't put it under `plex_search` it would probably just have its own catagory called `plex_collection` what do you think @mza921

**Comment by meisnate12** [comment]
this can be closed

**Comment by bigdork** [comment]
Thanks again!

**Comment by meisnate12** [comment]
hey @bigdork i have a performance upgrade in the works i'd love if youd test it out for me https://github.com/meisnate12/Plex-Auto-Collections/tree/PerformanceUpdate

**Comment by bigdork** [comment]
@meisnate12 I'll go check it out - the performance update is specifically for IMDb/tmdb list-based collections, correct? Or should there be improvements elsewhere?

**Comment by meisnate12** [comment]
Unfortunately it's just for the IMDb tmdb and Trakt lists

**Comment by bigdork** [comment]
@meisnate12 - I've noticed it works significantly faster. No benchmark, but in-particular this "cache" process runs much, **much** faster:
| Processing imdb_list: https://www.imdb.com/search/title/?groups=top_250
| 250 Movies found on IMDb
```
| Cache | + | plex://movie/5d776834f54112001f5bd580 | None | None | Van Wilder 2: The Rise of Taj
| Cache | + | plex://movie/5d7768458a7581001f12f69b | None | None | Van Wilder: Freshman Year
| Cache | + | plex://movie/5d7768373c3c2a001fbcea7b | None | None | Vanity Fair
| Processing: 23818/25299 Vasermil  
```
Incidentally, these items that appear in this process, is it that there's something wrong with their metatada in my Plex library?

**Comment by meisnate12** [comment]
The cached items are what was added to a cache for the new movie agent if you see other lines that say the IMDb if wasn't found then those won't be able to be matched to any IMDb tmdb or trakt attribute
