### ISSUE TITLE
v2.4.7 Docker not able to pull data from TMDB

### ISSUE THREAD

**Issue by SerinitySW** [mza921/Plex-Auto-Collections#108]
Just found this project today, looks absolutely fantastic. While I have gotten IMDB lists to work beautifully, TMDB collections don't seem to want to work. In the logs I get the following:

```
update_from_config(config_path, plex, True, args.no_meta, args.no_images)
| Processing tmdb_collection: 120794
File "/app/plex_auto_collections.py", line 461, in update_from_config
missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
File "/app/plex_tools.py", line 156, in add_to_collection
movies, missing = imdb_tools.tmdb_get_movies(config_path, plex, value, method)
File "/app/imdb_tools.py", line 133, in tmdb_get_movies
t_col = tmdb.details(tmdb_id)
File "/usr/local/lib/python3.9/site-packages/tmdbv3api/objs/list.py", line 13, in details
return self._get_obj(
File "/usr/local/lib/python3.9/site-packages/tmdbv3api/tmdb.py", line 101, in _get_obj
raise Exception(result["status_message"])
Exception: The resource you requested could not be found.
```

This is being run on a test server with a working tmdb API key. It seems for whatever reason the docker doesn't have the correct dependencies? Like I said, it's confirmed working with IMDB lists. Host OS is unRAID 6.8.3.

**Comment by meisnate12** [comment]
so i can run that exact collection just fine. I'm really not sure why its failing for you. It could be some kind of permission issue can you post your whole config?

**Comment by burkasaurusrex** [comment]
I'm having the same issue, exact same environment. @SerinitySW are you using Plex's new matching agent or the old matching agent?

**Comment by SerinitySW** [comment]
@meisnate12 Sure can: https://pastebin.com/RUjwqxFX
https://i.imgur.com/QLQIELa.png

@burkasaurusrex Yep, I'm on the new metadata agent, switched over a few days after it came out. Loving it so far, except that it broke IMDBList2Plex for me, which somehow led me to finding this muuuuch better solution.

**Comment by meisnate12** [comment]
Are you both running this in docker? If so can you try and rub the script using just python and see if you have the same issue?

**Comment by SerinitySW** [comment]
@meisnate12 I'm on docker, yep. I downloaded the python version instead on my Windows 10 PC (unRAID makes it hard to run python scripts like this on without docker) using the same config file. Nothing seems to happen when I run the command, no logging in powershell or anything. `python.exe .\plex_auto_collections.py`. All dependencies installed successfully. Python 3.8-32.

**Comment by burkasaurusrex** [comment]
Ok, I think I found the issue. It looks `tmdb_collection` might be mapping to `tmdb_list`?

I just got this TMDb collection to run, but it's actually running as a list:
```
| Updating collection: Ace Ventura...
| Sync Mode: append
| 
| Processing tmdb_collection: 3167
| Ace Ventura Collection | = | The Longest Yard
| Ace Ventura Collection | = | Her
| Ace Ventura Collection | = | Frozen
| Ace Ventura Collection | = | Rush
| Ace Ventura Collection | = | 300
| Ace Ventura Collection | = | Fargo
| Ace Ventura Collection | = | Homefront
| Ace Ventura Collection | = | Dawn of the Planet of the Apes
| Ace Ventura Collection | = | Rise of the Planet of the Apes
| Ace Ventura Collection | = | Batman Begins
| Ace Ventura Collection | = | The Dark Knight
| Ace Ventura Collection | = | The Dark Knight Rises
| Processed 12 Movies
| 5 missing movies from TMDb Collection: 3167
| Adding missing movies to Radarr
| --- Admission: This movie has already been added 400
| --- 300: Rise of an Empire: This movie has already been added 400
| --- We're No Angels: This movie has already been added 400
| --- The Odd Life of Timothy Green: This movie has already been added 400
| --- The Incredible Burt Wonderstone: This movie has already been added 400
```

List: https://www.themoviedb.org/list/3167
Collection: https://www.themoviedb.org/collection/3167

**Comment by burkasaurusrex** [comment]
Just tested `tmdb_id` and got the same result - `get_method_pair_tmdb` or `tmdb_get_metadata` might be the culprit

**Comment by burkasaurusrex** [comment]
@meisnate12 it looks like this is the problem:

https://github.com/mza921/Plex-Auto-Collections/blob/22bd7da5b306cd5ba309b6a2e4237d7b10aea7db/app/plex_tools.py#L155-L156

https://github.com/mza921/Plex-Auto-Collections/blob/22bd7da5b306cd5ba309b6a2e4237d7b10aea7db/app/imdb_tools.py#L123

https://github.com/mza921/Plex-Auto-Collections/blob/22bd7da5b306cd5ba309b6a2e4237d7b10aea7db/app/imdb_tools.py#L131

It looks like every call to `tmdb_get_movie` is overriding `is_list` to true, so everything is assumed to be a list instead of a collection. There needs to be logic built in `add_to_collection` or `tmdb_get_movie` to handle different methods. No idea if `tmdb_movie` or `tmdb_company` work properly, but I'd guess that they probably default to lists right now as well?

**Comment by meisnate12** [comment]
Ok so I've already changed this and fixed this in my next update lol

**Comment by meisnate12** [comment]
Ok I see some of my changes for my next push accidentally got mixed into the code on of the rebases and bug fixes I did. I'm remind the is_list in favor of just passing the method. I'm pretty much done with the update I just need to write the readme

**Comment by meisnate12** [comment]
this can be closed

**Comment by SerinitySW** [comment]
Closed, problem resolved
