### ISSUE TITLE
Disable Plex GUID cache on old agents

### ISSUE THREAD

**Issue by burkasaurusrex** [mza921/Plex-Auto-Collections#109]
I'm still on the old movie agent and probably will be for some time. Any way we could detect the agent used for the library and only attempt to use the cache if it's the new agent?

**Comment by burkasaurusrex** [comment]
It looks like we might be able to pull `agent` or `scanner` here: https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection

**Comment by burkasaurusrex** [comment]
Also, it looks like you can pull `type`? Probably could write out that setting under `plex` and just infer it from the API

**Comment by mza921** [comment]
One problem is that it's possible to have a movie in the library still use the new agent even if the library's default is the legacy agent.

**Comment by burkasaurusrex** [comment]
Oh crazy. So I haven't migrated my libraries yet - it's possible that newer movies are still being matched by the new agent?

**Comment by meisnate12** [comment]
it shouldn't be if you're still using the old agent. all we have to do for this is only create the cache once a movie of the new agent is found
