### ISSUE TITLE
Unraid Docker Creating New Containers When I Run the Script?

### ISSUE THREAD

**Issue by JakeLadson** [mza921/Plex-Auto-Collections#111]
Hello,

When I run the command `docker run -v '/mnt/user/plex-auto-collections/':'/config':'rw' 'mza921/plex-auto-collections' -u` a new docker container is created. Sorry, I'm new to this but wondering what I can run to update my library without creating a new container every time. Bellow is an image of what is happening.

![image](https://user-images.githubusercontent.com/26978529/98836989-0361a000-2408-11eb-935f-a080319a108b.png)

Thanks

**Comment by mza921** [comment]
`docker run` is supposed to create a new container each time. Add the `--rm` parameter to automatically delete it after it runs. I will add this to the README.
