### ISSUE TITLE
Movies not adding to Collection but are present in Library

### ISSUE THREAD

**Issue by b101marc** [mza921/Plex-Auto-Collections#114]
Hi all,

Have the latest build working beautifully with the updated Plex Movie Agent. Kudos to all for getting this working again.

I am having an issue with random titles not adding in to my Collections during scan. 

**List being used:**
https://trakt.tv/users/hammers-lists/lists/music-heavy-movies

**Titles stated as missing but are in Library:**
| --- Alvin and the Chipmunks
| --- The Blues Brothers
| --- Alvin and the Chipmunks: Chipwrecked
| --- Alvin and the Chipmunks: The Squeakqued
| --- Walk the Line
| --- Tenacious D in The Pick of Destiny
| --- This Is It
| --- Coyote Ugly
| --- Blues Brothers 2000
| --- Evita
| --- Hustle & Flow
| --- Labyrinth
| --- The Dirt
| --- The Doors
| --- Eddie and the Cruisers
| --- Purple Rain
| --- The Pirate Movie
| --- Jailhouse Rock
| --- Bye Bye Birdie
| --- Godspell
| --- Pink Floyd: The Wall
| --- The Idolmaker
| --- Fear of a Black Hat
| --- That Thing You Do!
| --- Hair
| --- The Commitments
| --- Hard Rock Zombies
| --- A Hard Day's Night
| --- La Bamba
| --- Tapeheads
| --- Airheads
| --- Crazy Heart
| --- Once
| --- The Bodyguard
| --- Rudderless
| --- Clubland
| --- Ricki and the Flash
| --- Walk Hard: The Dewey Cox Story
| --- Still Crazy

Any guidance appreciated.

**Comment by burkasaurusrex** [comment]
Do you mind posting the Plex XML files of one of these movies? You need to navigate to the media in Plex, click on the `...` "More" menu > `Get Info` > `View XML` (for reference: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats)

Please post it here as code (start paste with first line as \`\`\`xml and last line as \`\`\`)

**Comment by burkasaurusrex** [comment]
Actually an XML file for a movie that worked and a movie that didn't work would be helpful

**Comment by meisnate12** [comment]
I think this might be a duplicate issue that has a fix in the next release

**Comment by b101marc** [comment]
Posted them using pastebin

Working: https://pastebin.com/rqeeC6JX

Non-working: https://pastebin.com/Hq1zEZS7

thanks for taking the time.

**Comment by mza921** [comment]
In the non-working XML, I'm not seeing the `Guid` tag that would allow the script to match it. Maybe refreshing the metadata or scanning it in again might add it.

**Comment by b101marc** [comment]
that seems to have done the trick, however it still missed movies because despite doing a complete refresh of my library it still didn't update the metadata on who knows how many items.

Thank you, and thanks for this script!

**Comment by burkasaurusrex** [comment]
@mza921 it looks like they're both there?

Working: `guid="plex://movie/5d77682685719b001f3a0a6b"`
Non-working: `guid="plex://movie/5d776826961905001eb90fd2"`

**Comment by b101marc** [comment]
Looks like my issue isn't related to the script but this issue [#159](https://github.com/l3uddz/plex_autoscan/issues/159) due to using PlexAutoScan. Plex also touches on the topic [here.](https://forums.plex.tv/t/incomplete-movie-matching-on-new-plex-agent/653922/15?u=pawneevideodome)

**Comment by mza921** [comment]
Thanks for following up on the root cause.
