### ISSUE TITLE
Question about "content_rating"

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#119]
Question: Is content_rating: the Plex (5 star) rating, or is it IMDb/TMDb/RT rating?

**Comment by meisnate12** [comment]
Content_rating is based on whatever is in plex's content rating field which if pulled from tmdb would be like G, PG, PG-13, R but you can really put whatever you want there

**Comment by bigdork** [comment]
Whoops! Disregard.
