### ISSUE TITLE
"tmdb_network" Not grouping all TV Series

### ISSUE THREAD

**Issue by jkristoph** [mza921/Plex-Auto-Collections#121]
I notice that using thetmdb_network type collection does not group all available tv shows rather, seems to poll just a few.

**Comment by meisnate12** [comment]
What's the id of the network your'e trying to use?

**Comment by jkristoph** [comment]
E.g. from my config....

ABC:
    tmdb_network: 2
  BBC Three:
    tmdb_network: 3
  BBC One:
    tmdb_network: 4
  NBC:
    tmdb_network: 6
  ITV:
    tmdb_network: 9
  Nickelodeon:
    tmdb_network: 13
  PBS:
    tmdb_network: 14
  CBS:
    tmdb_network: 16
  FOX:
    tmdb_network: 19
  The WB:
    tmdb_network: 21
  USA Network:
    tmdb_network: 30
  MTV:
    tmdb_network: 33
  Lifetime:
    tmdb_network: 34
  TNT:
    tmdb_network: 41
  National Geographic:
    tmdb_network: 43
  Comedy Central:
    tmdb_network: 47
  HBO:
    tmdb_network: 49
  Disney Channel:
    tmdb_network: 54
  Spike:
    tmdb_network: 55
  Cartoon Network:
    tmdb_network: 56
  CNN:
    tmdb_network: 59
  Discovery:
    tmdb_network: 64
  History:
    tmdb_network: 65
  Showtime:
    tmdb_network: 67
  TBS:
    tmdb_network: 68
  The CW:
    tmdb_network: 71
  Bravo:
    tmdb_network: 74
  ABC Family:
    tmdb_network: 75
  E!:
    tmdb_network: 76
  Syfy:
    tmdb_network: 77
  Adult Swim:
    tmdb_network: 80
  FX:
    tmdb_network: 88
  Animal Planet:
    tmdb_network: 91
  BBC Four:
    tmdb_network: 100
  IFC:
    tmdb_network: 124
  A&E:
    tmdb_network: 129
  Oxygen:
    tmdb_network: 132
  Food Network:
    tmdb_network: 143
  ITV2:
    tmdb_network: 149
  AMC:
    tmdb_network: 174
  HGTV:
    tmdb_network: 210
  Starz:
    tmdb_network: 318
  Cinemax:
    tmdb_network: 359
  Hulu:
    tmdb_network: 453
  Amazon:
    tmdb_network: 1024
  Netflix:
    tmdb_network: 213
  Disney+:
    tmdb_network: 2739

For example, ABC, has matched 17 Shows, yet Plex search for ABC network has, 321 Shows

**Comment by meisnate12** [comment]
i see the problem the program isnt pageing correctly i should have this fixed for the next update

**Comment by jkristoph** [comment]
Amazing, I am also getting timeout errors. I will create another issue to track.
