### ISSUE TITLE
Enhancement: plex_collection.not filter not supported

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#123]
Not a big deal, but came across this. I've found another way to do what I need, but this would be helpful.
`| Config Error: plex_collection.not filter not supported`

**Comment by meisnate12** [comment]
I think I could manage to add this in. I'm super curious what collection were you trying to make using this?

**Comment by bigdork** [comment]
```
collections:
  Mature Animation:
    genre: Animation
    filters:
      plex_collection.not: [Kids Animation, Anime]
```
;)
