### ISSUE TITLE
Fails to Start the process running

### ISSUE THREAD

**Issue by roshanconnor123** [mza921/Plex-Auto-Collections#125]
Hello there
First of all, Thank you very much for this wonderful tool
So I followed the instructions and created a config.yml in `app` folder as well as in `config` folder
Then I ran this command
```
python plex_auto_collections.py
```
I was met with the following error -> https://del.dog/iningafynu.txt

Here is my Config File - https://del.dog/yckuximanu.txt

Please help me fix this issue

Thank you

**Comment by meisnate12** [comment]
YML files are based on spaces so when you intend with tab it will throw an error. You need to go through the config and replace all the white space with spaces over tabs

**Comment by meisnate12** [comment]
I added a better error message to the program
