### ISSUE TITLE
Any way to print a list of missing movies rather than adding to Radarr

### ISSUE THREAD

**Issue by wisem2540** [mza921/Plex-Auto-Collections#126]
Looking for a way for script to "print", or write to the console the list of movies it thinks are missing from the list.  Alot of my missing movies have "year" discrepancies like IMBD says 2010, Plex says 2011, so I dont want them added to radarr.  I need an opportunity to correct them.

Advice?  Or maybe simply a quick enhancement?

**Comment by meisnate12** [comment]
if the movie is in your library and mapped properly it shouldn't be added to the missing list. You should see any mapping errors at the beginning of the run did you update to 2.7.0?

**Comment by wisem2540** [comment]
Still on 2.6. What's the most direct way to update using ubuntu CLI?

**Comment by meisnate12** [comment]
just do a git pull

**Comment by wisem2540** [comment]
I think this is working as expected.  I will keep playing with it.  Thanks for your quick response

**Comment by sean-marks** [comment]
If this is issue is resolved, seems it could be closed? :)
