### ISSUE TITLE
Using tool to update 2 separate plex servers not working

### ISSUE THREAD

**Issue by vitadome** [mza921/Plex-Auto-Collections#127]
Hello, 
Adding Collections to my initial server works fine, however, 2nd server provides ' x number of movies missing' message.  Any ideas on what I'm doing wrong?

My yaml I toggle between both servers.

plex:
  library: Movies
  library_type: movie ### 'movie' or 'show' ###
  # token: a4YzyLaefx5xxxxxxe7C
  # url: http://148.xxx..xxx.xxx:42447
  token: U-56QxxxxxxgtCQeBhXh
  url: http://116.xxx.xxx.xxx:42433
  sync_mode: append

My output is
=====================================================================
|
| Updating collection: Terminator...
| Sync Mode: append
|
| Processing imdb_list: https://www.imdb.com/list/ls086606952/
| 6 missing movies from IMDb List: https://www.imdb.com/list/ls086606952/
|
|
|=====================================================================

**Comment by meisnate12** [comment]
what agent is each using?

**Comment by vitadome** [comment]
They are both set up the same using TMDB.  I did a compare and everything seems to mirror each other.

![image](https://user-images.githubusercontent.com/58059772/100488511-ad198000-30dc-11eb-923e-a04e9f028e51.png)

**Comment by vitadome** [comment]
Adding some images to see if someone could help troubleshoot.

**config.png** shows plex section of code.  The commented section works fine.  The other token/url lines show "missing" in my output file.

**library.png** shows that I'm using TMDB agent (same setup as my other server)

**tautulli.png** shows where I'm pulling my authentication code in Tautulli.


![conifg](https://user-images.githubusercontent.com/58059772/101270794-91505280-374a-11eb-918b-aaa8bccdb427.png)
![library](https://user-images.githubusercontent.com/58059772/101270797-99a88d80-374a-11eb-8d41-386a7e42ec34.png)
![tautulli](https://user-images.githubusercontent.com/58059772/101270798-9f05d800-374a-11eb-9d32-06a3a1ce0c43.png)

**Comment by burkasaurusrex** [comment]
Have you upgraded to the new matching agent? And are you running the script on each server or running it from one server? If you’re running it from two different servers, please ensure that you’ve updated the Python requirements using the current requirements.txt

**Comment by vitadome** [comment]
It appears that I wasn't using version 2.6 -- I have since installed the latest version without issue.  My apologies for the fire drill.  Thanks for the support and feedback.
