### ISSUE TITLE
[Issue] Script reporting "No Movies Found" after update to 2.7.0

### ISSUE THREAD

**Issue by SerinitySW** [mza921/Plex-Auto-Collections#128]
I was running on the previous docker release, and upgraded tonight on a whim. I also added the new cache feature to my config. The script seems to successfully map my movies at the beginning (spare a few), but then can't find any movies anymore when looking through collections. For example:

```
Updating collection: Trending Globally...
| Sync Mode: sync
| 
| Processing trakt_trending: 50
| 50 Movies found on Trakt
| No Movies Found
| 50 missing movies from Trakt Trending: Top 50
| 
| Processing trakt_list: https://trakt.tv/users/linaspurinis/lists/top-watched-movies-of-the-week?sort=rank,asc
| 25 Movies found on Trakt
| No Movies Found
| 25 missing movies from Trakt List: https://trakt.tv/users/linaspurinis/lists/top-watched-movies-of-the-week?sort=rank,asc
| 
| Processing trakt_list: https://trakt.tv/users/linaspurinis/lists/imdb-moviemeter?sort=rank,asc
| 38 Movies found on Trakt
| No Movies Found
| 38 missing movies from Trakt List: https://trakt.tv/users/linaspurinis/lists/imdb-moviemeter?sort=rank,asc
| 
| Processing trakt_list: https://trakt.tv/users/linaspurinis/lists/top-watched-movies-of-the-week-for-kids?sort=added,asc
| 7 Movies found on Trakt
| No Movies Found
| 7 missing movies from Trakt List: https://trakt.tv/users/linaspurinis/lists/top-watched-movies-of-the-week-for-kids?sort=added,asc
```

This actually caused all movies to be removed on lists with 'sync' mode. Config for the above:

```
Trending Globally:
            trakt_trending: 50
            sync_mode: sync
            trakt_list:
                - https://trakt.tv/users/linaspurinis/lists/top-watched-movies-of-the-week?sort=rank,asc
                - https://trakt.tv/users/linaspurinis/lists/imdb-moviemeter?sort=rank,asc
                - https://trakt.tv/users/linaspurinis/lists/top-watched-movies-of-the-week-for-kids?sort=added,asc
```

However it doesn't work on any lists anymore. My config/the script were working beautifully on the previous update

**Comment by meisnate12** [comment]
is this only failing for trakt collections? or is it also failing with others like a tmdb collection

**Comment by meisnate12** [comment]
the biggest problem we're gonna have figuring out what's going on is the fact that I cant seem to replicate your error or the error in #124 i think they might be related, but its really hard to figure out whats going on when it all seems to be working fine for me

**Comment by meisnate12** [comment]
can you add this line in trakt_tools.py at line 52

```python
    print("\n", title_ids, "\n\n", plex_map, "\n")
```

it should change this
```python
51    title_ids = [int(m.get_key('tmdb')) for m in trakt_list_items if isinstance(m, trakt.objects.movie.Movie)]
52
53    print("| {} Movies found on Trakt".format(len(title_ids)))
```

to this
```python
51    title_ids = [int(m.get_key('tmdb')) for m in trakt_list_items if isinstance(m, trakt.objects.movie.Movie)]
52    print("\n", title_ids, "\n\n", plex_map, "\n")
53    print("| {} Movies found on Trakt".format(len(title_ids)))
```

can you run that with only the one trakt collection in your config and paste here the entire program output

**Comment by bigdork** [comment]
Happening here too, wiped out all trakt/tmdb/imdb movie lists that had sync enabled, including trakt trending. 
Also, tmdb_show and tvdb_show are not matching in TV collections.
Oddly, trakt trending for TV was unaffected?

**Comment by meisnate12** [comment]
trakt trending for TV should be broken i just noticed an error with it im surprised its working

**Comment by bigdork** [comment]
@meisnate12 Ah, I'd not run it to see, just noticed it wasn't wiped out like the other collections in Plex. That's probably why.
I may have time to troubleshoot this later tonight if @SerinitySW doesn't beat me to it.

**Comment by meisnate12** [comment]
but the weird part is the way that trakt TV was broken it should have wiped out those collections like it did the others but the others weren't suppoused to. Im so confused as to what is going on.

**Comment by SerinitySW** [comment]
> is this only failing for trakt collections? or is it also failing with others like a tmdb collection

It's also failing with IMDb lists

> can you add this line in trakt_tools.py at line 52

That... fixed it? Trakt is now matching...

https://pastebin.com/XQHtskXe

Unfortuantely I can't get a full output because unRaid's terminal is limited to so many characters, and the docker log has some of the characters cut off for some reason. Hopefully that gets the point across though.

IMDb, however, is still not matching:
```
|===================================================================================================|
|
| Updating collection: Comedy Films...
| Sync Mode: append
| 
| Processing imdb_list: https://www.imdb.com/search/title/?genres=comedy&groups=top_25000&sort=user_rating&title_type=feature&count=250
| 100 Movies found on IMDb
| No Movies Found
| 100 missing movies from IMDb List: https://www.imdb.com/search/title/?genres=comedy&groups=top_25000&sort=user_rating&title_type=feature&count=250
```

**Comment by mza921** [comment]
It doesn't look like tvdb_id is being converted to int for the plex_map lookup.

**Comment by SerinitySW** [comment]
Update: IMDb is also now matching. This is bizarre. I'll monitor it and keep the topic open for others to talk about their similar issues.

**Comment by SerinitySW** [comment]
Another update: All of a sudden, the docker log now shows the full text rather than cutting off the beginning. This was cut off in the previous version, too. Not complaining

**Comment by meisnate12** [comment]
you see what im saying this is all really weird i would try a fresh docker pull if you havent tried that already. It seems liek something isnt fully updated.

> 
> 
> It doesn't look like tvdb_id is being converted to int for the plex_map lookup.

thats the one error ive found but thats shouldnt be effecting the movies.

**Comment by darkknight6722** [comment]
I still have this issue. I`m using imdb list, trakt list, tvdb id and tautulli list. Only tautulli works.
[config](https://pastebin.com/sJsEvkTG)
[logs](https://pastebin.com/dpbQDU41)

**Comment by basketball00011** [comment]
Having same issue. Just started using this today, but can't get any trakt lists to show anything. I can use the "example' plex configs no problem.

`| 30 Movies found on Trakt
| No Movies Found
| 30 missing movies from Trakt Trending: Top 30
|
| Config Error: Collection Trakt Trending Not Found`

**Comment by mza921** [comment]
Rolling back the last update and creating a `performance` branch for additional testing.

**Comment by mza921** [comment]
I did see the similar behavior during the same timeframe these were reported, but have not been able to reproduce it since, even with no changes.

**Comment by darkknight6722** [comment]
Changing `cache` from `false` to `true` fixed it for me.
Can you add an hours option in `cache` instead of just days?

**Comment by darkknight6722** [comment]
But if a new movie gets added, I have to run this script twice to add those movies to plex. First time it gets added to cache and next  time it is added to plex. Is this the expected behaviour?

**Comment by mza921** [comment]
The `cache` option is removed in 2.8.0. I tried to distinguish between the GUID map (which is a database used to convert Plex GUIDs to IMDB and TMDB IDs solely for the new Plex agent) and the cache, which is initialized on every execution (supposed to benefit multiple collections within a config).

**Comment by darkknight6722** [comment]
Now again IMDB list, TMDB collection are not working. But Trakt list and TMDB director works. Anyone have same problems or its just me?

**Comment by mza921** [comment]
Pushed a fix.

**Comment by mza921** [comment]
Please give it another go.

**Comment by darkknight6722** [comment]
For me, Everything works.

**Comment by SerinitySW** [comment]
Everything is good - to - go now.
