### ISSUE TITLE
[Feature] Python-plexlibrary IMDB Support

### ISSUE THREAD

**Issue by wisem2540** [mza921/Plex-Auto-Collections#129]
Sorry to place this here, I could not find "issues" in the repo.

I have standardized on IMDB for use with Plex-Auto-Collections.  When using Auto-Collections, I ended up with 300 items in a collection, which seems a bit large.  I feel like this may warrant its own library.  So I found PythonPlex Library, which tells me you must have already thought of this!

Couple questions I have...  Does the script physically move the files to a different directory to be picked up by the auto scanner?  If not, is this a possibility?  I feel like it is ultimately cleaner, especially if plex stops supporting this function, or the script is no longer maintained.

As I said earlier, I have standardized on IMDB already, are there plans to implement support for this?

Lastly, I would love to donate.  As someone with some dev experience, I know the time you are putting into this.

**Comment by mza921** [comment]
Hello,

Python-PlexLibrary is a completely different project. This script doesn't modify any files. All the updates happen inside the Plex database. I'm not sure there's a way to automatically update what collections an item gets added to. This script is meant to be run on intervals to handle that. Can you clarify what you mean by standardizing on IMDB? This script currently supports collections based on IMDB lists and searches. See [this](https://github.com/mza921/Plex-Auto-Collections#imdb-list-or-search-list-type) part of the README.

**Comment by wisem2540** [comment]
Sorry for the confusion.  What I was trying to say was that I could not find the "issues" section for Python-PlexLibrary to report this.  But based on what I read, that project does not seem to support IMDB, althought I have not tested it

**Comment by sean-marks** [comment]
Seems this was opened in the wrong repo and could be closed?
