### ISSUE TITLE
Roll-back of docker broke image (Please update requirements using "pip install -r requirements.txt")

### ISSUE THREAD

**Issue by SerinitySW** [mza921/Plex-Auto-Collections#131]
The roll-back to 2.6.0 seems to have broken the docker image. This is all that shows up in my log now:

```
|
| Requirements Error: Please update requirements using "pip install -r requirements.txt"

|
```

Docker was working on 2.6.0 (pre-upgrade), 2.7.0.

**Comment by burkasaurusrex** [comment]
@mza921 can you delete the latest two builds so the latest is the original build of 2.6.0?

**Comment by mza921** [comment]
The latest build should already be based on 2.6.0. You might need to remove your docker image and pull it again.

**Comment by SerinitySW** [comment]
Re-pulling from scratch resolved the issue.
