### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by whatupcraig** [mza921/Plex-Auto-Collections#137]
Getting this error when trying to make a request through themoviedb. This is from the jurassic park example. 

| Processing tmdb_collection: (328) Jurassic Park Collection
| Cache | + | plex://movie/5f866989cf0e4600414eacd3 | tt13187916 | None | Burden
update_from_config(config_path, plex, True, args.no_meta, args.no_images)
File "/app/plex_auto_collections.py", line 615, in update_from_config
missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
File "/app/plex_tools.py", line 151, in add_to_collection
movies, missing = imdb_tools.tmdb_get_movies(config_path, plex, value, method)
File "/app/imdb_tools.py", line 252, in tmdb_get_movies
if int(tmdb_id) == int(mid):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by jolbol1** [comment]
Had a similar issue and had to manually fix match to tmdb in plex. For your case this looks like it's the movie Burden.

**Comment by whatupcraig** [comment]
> Had a similar issue and had to manually fix match to tmdb in plex. For your case this looks like it's the movie Burden.

This fiixed it btw. Thank you.
