### ISSUE TITLE
AttributeError: module 'imdb_tools' has no attribute 'imdb_get_tmdb' 

### ISSUE THREAD

**Issue by NBSDEVApp** [mza921/Plex-Auto-Collections#147]
Hello, since today I get a new error (docker):

> Mapping Plex Movies
| Processing: 9/519 2001: A Space Odyssey     
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/app/plex_auto_collections.py", line 120, in update_from_config
    plex_map = get_map(config_path, plex)
  File "/app/plex_tools.py", line 125, in get_map
    key_id = imdb_tools.imdb_get_tmdb(config_path, check_id)
AttributeError: module 'imdb_tools' has no attribute 'imdb_get_tmdb'

Thanks for helping me ;)

///My config///
collections:              
    Cyberpunk:
        trakt_list:
          - https://trakt.tv/users/missletwiss/lists/cyberpunk
          - https://trakt.tv/users/liipesilva/lists/cyberpunk-movies-and-shows
        collection_order: alpha
plex:
    library: Movies
    library_type: movie
    token: mytoken
    url: https://server
    sync_mode: append
radarr:
    url: https://server
    token: mytoken
    quality_profile_id: 3
    root_folder_path: /mnt/unionfs/Media/Movies
    add_to_radarr: false
    search_movie: false
    version: v3
tmdb:
    apikey: myapi
    language: en
tautulli:
    url: https://server
    apikey: myapi
trakt:
    client_id: myid
    client_secret: myid
    auto_refresh_token: true
  # Below is filled in automatically when the script is run
    authorization:
        access_token: mytoken
        token_type: Bearer
        expires_in: 7889237
        refresh_token: mytoken
        scope: public
        created_at: 1608071841
image_server:
    poster_directory: ../config/posters
    background_directory: ../config/backgrounds
    image_directory: ../config/images

**Comment by NBSDEVApp** [comment]
Yesterday I have got no issue, Idk why he block on this movie (I have try with other config too)

**Comment by sean-marks** [comment]
Updated from 2.6 to 2.8 - getting the following error when running the first collection.

| Updating collection: IMDb Top 250...
| Sync Mode: sync
|
| Processing imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=25
Traceback (most recent call last):
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_auto_collections.py", line 1026, in
update_from_config(config_path, plex, True, args.no_meta, args.no_images)
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_auto_collections.py", line 668, in update_from_config
missing, map = add_to_collection(config_path, plex, m, v, c, plex_map, map, filters)
File "/mnt/user/appdata/Plex-Auto-Collections/app/plex_tools.py", line 242, in add_to_collection
items, missing = imdb_tools.imdb_get_movies(config_path, plex, plex_map, value)
AttributeError: module 'imdb_tools' has no attribute 'imdb_get_movies'

**Comment by mza921** [comment]
Had an issue with the merge. Looking into it now.

**Comment by sean-marks** [comment]
Fixed my issue with 2.8.1, thanks a ton!

**Comment by NBSDEVApp** [comment]
I still have the issue

**Comment by mza921** [comment]
1. What version are you using?
2. Are you using docker?
3. Do you have updated output of the error or is it the same?

**Comment by NBSDEVApp** [comment]
I use the docker version "docker run --rm -v '/opt/plex-auto-collections/':'/config':'rw' 'mza921/plex-auto-collections' -u" 
So I suppose it's the last version.
The error is the same, I have try to clean cache and DB too.

**Comment by mza921** [comment]
You could still be on a previous version. Check the output of the script, under the Plex Auto Collections ASCII art. Or you can run `docker rmi <image-id>` and rerun your command to pull the image.

**Comment by NBSDEVApp** [comment]
" Version 2.6.0" oh I'm not updated

**Comment by NBSDEVApp** [comment]
All work fine in the last update. Thanks for your work
