### ISSUE TITLE
Script failing to find imdb_id

### ISSUE THREAD

**Issue by pekempy** [mza921/Plex-Auto-Collections#15]
Hi all,

Trying this out for the first time, added a coulple of Trakt lists and kept the default Jurassic park TMDB list. I'm getting the below error that entries['imdb_id'] isn't found in movie details.

Removing the tmdb list and using trakt works however
```==================================================================
 Plex Auto Collections by /u/iRawrz
==================================================================
Attempting to start image server
IMAGE SERVER NOT RUNNING
Update Collections from Config? (y/n): y
Updating collection: Jurassic Park...
Processing tmdb-list: https://www.themoviedb.org/collection/328
Traceback (most recent call last):
  File "plex_auto_collections.py", line 217, in <module>
    update_from_config(config_path, plex)
  File "C:\Users\Administrator\Downloads\Plex-Auto-Collections-master\config_tools.py", line 125, in update_from_config
    missing = add_to_collection(config_path, plex, m, v, c, subfilters)
  File "C:\Users\Administrator\Downloads\Plex-Auto-Collections-master\plex_tools.py", line 133, in add_to_collection
    movies, missing = imdb_tools.tmdb_get_movies(config_path, plex, value)
  File "C:\Users\Administrator\Downloads\Plex-Auto-Collections-master\imdb_tools.py", line 103, in tmdb_get_movies
    imdb_id = t_movie.details(mid).entries['imdb_id']
AttributeError: 'AsObj' object has no attribute 'entries'  
```

I'm not sure what's causing this, I've ensured the plexapi is installed along with all other requirements.
This is my config.yml (censored)
```collections:
  Jurassic Park:
    tmdb-list: https://www.themoviedb.org/collection/328
    details:
      tmdb-summary: 328
      poster: https://i.imgur.com/QMjbyCX.png
  Marvel Cinematic Universe:
    trakt-list: https://trakt.tv/users/tetharion/lists/marvel-cinematic-universe
    details: 
        poster: https://i.imgur.com/S6Ohqaw.png
  Disney Animated:
    trakt-list: https://trakt.tv/users/kombat/lists/disney-animation
    details:
        poster: https://i.imgur.com/6tZJs1t.png
plex:
  library: Films
  library_type: 'movie'
  token: ################
  url: http://192.168.1.235:32400
radarr:
  url: http://192.168.1.235:7878/radarr/
  token: #################################
  quality_profile_id: 4
  root_folder_path: /CaveJ-Movies/
  search: false
tmdb:
  apikey: #################################
  language: en
trakt:
  client_id: #################################
  client_secret: #################################
  # Below is filled in automatically when the script is run
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:
image-server:
  host: 0.0.0.0
  port: 5000
```

**Comment by pekempy** [comment]
Another error I get is adding to radarr
```
Add missing movies to Radarr? (y/n): y
Traceback (most recent call last):
  File "plex_auto_collections.py", line 217, in <module>
    update_from_config(config_path, plex)
  File "C:\Users\Administrator\Downloads\Plex-Auto-Collections-master\config_tools.py", line 142, in update_from_config
    add_to_radarr(config_path, missing)
  File "C:\Users\Administrator\Downloads\Plex-Auto-Collections-master\radarr_tools.py", line 75, in add_to_radarr
    if response.json()[0]['errorMessage'] == "This movie has already been added":
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by burkasaurusrex** [comment]
It sounds like it's an issue with your TMDb API key? Please refer to the document here: https://developers.themoviedb.org/3/getting-started/introduction

**Comment by pekempy** [comment]
> 
> 
> It sounds like it's an issue with your TMDb API key? Please refer to the document here: https://developers.themoviedb.org/3/getting-started/introduction

That was it, I thought they were auto approved but it seems it was only approved this morning! Thanks for the reply.

**Comment by ExDominatus** [comment]
> It sounds like it's an issue with your TMDb API key? Please refer to the document here: https://developers.themoviedb.org/3/getting-started/introduction

I'm sorry, I'm getting the same error with imdb and tmdb lists. What am I supposed to be looking for in this doc?

> That was it, I thought they were auto approved but it seems it was only approved this morning! Thanks for the reply.

How did you get your API key approved? From what I'm reading, you just go into your account settings and generate an API key. I'm not seeing anything about approval.

The same errors for reference:

```Update Collections from Config? (y/n): y
Updating collection: Jurassic Park...
Processing tmdb-list: https://www.themoviedb.org/collection/328
Traceback (most recent call last):
  File "plex_auto_collections.py", line 217, in <module>
    update_from_config(config_path, plex)
  File "/home/ExD/Plex-Auto-Collections/config_tools.py", line 137, in update_from_config
    missing = add_to_collection(config_path, plex, m, v, c, subfilters)
  File "/home/ExD/Plex-Auto-Collections/plex_tools.py", line 133, in add_to_collection
    movies, missing = imdb_tools.tmdb_get_movies(config_path, plex, value)
  File "/home/ExDr/Plex-Auto-Collections/imdb_tools.py", line 103, in tmdb_get_movies
    imdb_id = t_movie.details(mid).entries['imdb_id']
AttributeError: 'AsObj' object has no attribute 'entries'```

**Comment by pekempy** [comment]
> 
> 
> > It sounds like it's an issue with your TMDb API key? Please refer to the document here: https://developers.themoviedb.org/3/getting-started/introduction
> 
> I'm sorry, I'm getting the same error with imdb and tmdb lists. What am I supposed to be looking for in this doc?
> 
> > That was it, I thought they were auto approved but it seems it was only approved this morning! Thanks for the reply.
> 
> How did you get your API key approved? From what I'm reading, you just go into your account settings and generate an API key. I'm not seeing anything about approval.
> 
> The same errors for reference:
> 
> ```
> Updating collection: Jurassic Park...
> Processing tmdb-list: https://www.themoviedb.org/collection/328
> Traceback (most recent call last):
>   File "plex_auto_collections.py", line 217, in <module>
>     update_from_config(config_path, plex)
>   File "/home/ExD/Plex-Auto-Collections/config_tools.py", line 137, in update_from_config
>     missing = add_to_collection(config_path, plex, m, v, c, subfilters)
>   File "/home/ExD/Plex-Auto-Collections/plex_tools.py", line 133, in add_to_collection
>     movies, missing = imdb_tools.tmdb_get_movies(config_path, plex, value)
>   File "/home/ExDr/Plex-Auto-Collections/imdb_tools.py", line 103, in tmdb_get_movies
>     imdb_id = t_movie.details(mid).entries['imdb_id']
> AttributeError: 'AsObj' object has no attribute 'entries'```
> ```

The next day I got a notification on tmdb that my API key was approved, I was also under the impression a generated one would just "work", but once it was approved tmdb lists worked

**Comment by burkasaurusrex** [comment]
I think there was a breaking change or regression in the python package `tmdbv3api`. @pekempy can you run the following command?

`pip show tmdbv3api` and post the output here?

If the `version` shown in the output is 1.6.0 or 1.6.1, try doing the following:

```
pip uninstall tmdbv3api
pip install tmdbv3api==1.5.1
```
