### ISSUE TITLE
Automate "Add missing movies to radarr"

### ISSUE THREAD

**Issue by pekempy** [mza921/Plex-Auto-Collections#16]
An option in the `config.yml` for adding to radarr y/n would be nice, if it's not in already. Would save having to confirm yes or no for each collection

**Comment by burkasaurusrex** [comment]
Just run it with the `--update` option and it will run without any user interaction.

```python
python plex_auto_collections.py --update
```

**Comment by ExDominatus** [comment]
Running it with the --update option doesn't automatically add to Radarr, I don't think, atleast when I tested it.

**Comment by pekempy** [comment]
Just testing with --update now to test what ExDominatus said - it appears to not attempt adding to radarr with --update flag. It just seems to say "37 missing movies from Trakt List _________"

To elaborate a bit, some collections I would like to add to radarr any missing films, but others I would like to prevent films being added.
Say collection A has 12 missing movies not in Radarr, and collection B has 128 missing movies, I'd want to add them from A but not B

**Comment by ExDominatus** [comment]
So not quite the elegant solution you are looking for pekempy, but you could pass in a pre-setup strings of yes's and no's to the script for when it prompts you.

`printf 'y\ny\ny\nn\nq\n' | your collection command here`

In the example command above, you are passing in three `y` followed by a newline (an enter, basically) `\n` followed by an `n` followed by a `q` to quit the script, as it prompts you. There are also other ways of passing in inputs using files, premade commands, echo, yes, etc, but hopefully this gets you started in the right direction.

**Comment by burkasaurusrex** [comment]
Oh, just realized I never pushed the change to fix this. Will update the readme and push the change later tonight.

**Comment by pekempy** [comment]
> 
> 
> So not quite the elegant solution you are looking for pekempy, but you could pass in a pre-setup strings of yes's and no's to the script for when it prompts you.
> 
> `printf 'y\ny\ny\nn\nq\n' | your collection command here`
> 
> In the example command above, you are passing in three `y` followed by a newline (an enter, basically) `\n` followed by an `n` followed by a `q` to quit the script, as it prompts you. There are also other ways of passing in inputs using files, premade commands, echo, yes, etc, but hopefully this gets you started in the right direction. And remember the first `y` is when the script prompts you to build collection from config. Adding to radarr is second `y` onwards.

Yeah this may be how I end up doing it then, I'll give it a test :)

**Comment by burkasaurusrex** [comment]
Just pushed my fix for this in [my repo](https://github.com/burkasaurusrex/Plex-Auto-Collections) if you want to take a look before it's merged in. Just add `add_movie: true` to the `radarr` block in the `config.yml` and it should work.

**Comment by pekempy** [comment]
@burkasaurusrex  does that work per collection though?

**Comment by burkasaurusrex** [comment]
No, it's all or nothing right now. I plan to eventually build the collection-by-collection mechanism that would override the config-level setting.

In the meantime, you could have two separate config files - one that adds movies to radarr and one that does not - and the call them with command line switch.
