### ISSUE TITLE
Best strategy for movies and collection visibility

### ISSUE THREAD

**Issue by henningBunk** [mza921/Plex-Auto-Collections#174]
Hi there,
I am making heavy use on collections and woud like to know how you are handling the visibility settings of your movies and collections.

I have two kind of collections: 
1. A regular movie series, like Jurassic Park. I want to display the collection but not the individual movies
2. Movies lists as collections, like the IMDb Top 250 or every movie of one director. I want to display the collection and I want to display the individual movie.

Setting the Jurassic Park Collection to "Hide elements of collection" and the IMDb Top 250 to "Show collection and it's elements" works fine, as long as a movie only in one of these collections.  
But the movie Jurassic Park belongs to both of these collections, unfortunatly it is enough for a movie to be in one collection which is set to "Show collection and it's elements" for it to appear in the regular movie list, although I would like to hide it because it's in the Jurassic Park collection.

Right now I am managing visibillity manually by having the default visibility for all my collections to "Hide elements of collection" and having one collection which is called "Visible" with the other setting.  
A movie like Jurassic Park I would set the collections to "Jurassic Park Collection" and "IMDb Top 250", it would not appear in the regular movie list like I want it to.  
A movie like 12 Angry Men I would set the collections to "IMDb Top 250" and "Visible", it would also appear in the regular movie list like I want it to.

How do you manage your visibilities? Would it be possible to recreate the behaviour with this script?

**Comment by ramair02** [comment]
This can totally be managed with the script: https://github.com/mza921/Plex-Auto-Collections#collection-mode-collection-attribute. It can also be managed manually by Collection in Plex. Just go into Edit for an individual Collection, go to Advanced and choose from the Collection Mode dropdown.

Sounds like you want Jurassic Park to be set as `hide_items` or Hide items in this Collection. And for IMDb Top 250, you want `show_items` or Show this Collection and it's items.

**Comment by BlueSkillZ99** [comment]
@henningBunk, how you are doing it, is afaik the best/only way. But how to add every new movie not belonging into a regular collection (1.) to that one „Visible„ collection? I have not found an efficient and automated approach. We would need a way to search/filter for movies NOT belonging to any collection, before the scripts adds it to any special collection (2.). Or for movies not belonging to any tmdb_collection

@ramair02 Setting the Top250 collection to show_items does not work, as it always overrides the hide_item settings. All movies that are in both collections would be shown, but he wants to keep them hidden. And as all new collections will use hide_items, this is just the default library behavior and nothing needs to be specified in the script

**Comment by ramair02** [comment]
@BlueSkillZ99 I stand corrected! I did not read the original post thoroughly and mistakenly assumed this was a general collection mode question. 

@henningBunk You can disregard my advice ;)

**Comment by henningBunk** [comment]
> But how to add every new movie not belonging into a regular collection (1.) to that one „Visible„ collection? 

Thats the crux. Without it I fear that that new movies gets added to some big collections like the IMDb Top 250 and therefore are getting hidden from everywhere else.

**Comment by BlueSkillZ99** [comment]
Don‘t be too worried too much. This setting only affects the library view if sorted by Title and have no filters applied. As soon as you sort or filter all movies and no collection are shown. With a couple thousand movies in the library I rarely find myself scrolling through the whole library in alphabetical order.

**Comment by henningBunk** [comment]
> With a couple thousand movies in the library I rarely find myself scrolling through the whole library in alphabetical order.

What? This is my greatest hobby!

I think I will adjust to a different strategy:
* Forget the 'Visible' collection
* Set all my collections to 'Hide this collection'

That way I get a list of all movies in the movies tab and all collections in the collections tab, I think I'll like that.

Thanks for your input, I will close this topic :)
