### ISSUE TITLE
To do: Sync with various lists instead of append-only

### ISSUE THREAD

**Issue by burkasaurusrex** [mza921/Plex-Auto-Collections#22]
The script currently only allows for appending missing media to a collection. It would be cool to be able to sync -- append missing and remove extras. It could be accomplished today by deleting the collection and then running the current append-only script. Instead of destroying and recreate the collection everytime, it seems like it would be better to update the existing collection to maintain any collection-level settings that the user has set in Plex directly.

**Comment by meisnate12** [comment]
this can be closed
