### ISSUE TITLE
Duplicate Key

### ISSUE THREAD

**Issue by AwesomeAustn** [mza921/Plex-Auto-Collections#224]
I'm not sure what this means. Could someone help me understand it?

`    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "<unicode string>", line 7, column 5:
        TMDb Popular:
        ^ (line: 7)
found duplicate key "Comedy" with value "ordereddict([('all', True), ('filters', ordereddict([('genre', 'Comedy')])), ('sync_mode', 'sync'), ('collection_mode', 'default'), ('collection_order', 'alpha'), ('sort_title', '*200'), ('summary', 'A collection of Comedy TV Shows')])" (original value: "ordereddict([('tmdb_discover', ordereddict([('with_genres', 35)])), ('sync_mode', 'sync'), ('collection_mode', 'default'), ('collection_order', 'alpha'), ('sort_title', '*150')])")
  in "<unicode string>", line 63, column 5:
        Comedy:
        ^ (line: 63)`

**Comment by meisnate12** [comment]
You're using Comedy as the name of two collections.

**Comment by AwesomeAustn** [comment]
Thanks! I was confused with "line 7, column 5" because that's the beginning of my TMDb Popular collection that uses tmdb_discover and it has nothing to do with Comedy. I disabled one of my Comedy ones.

**Comment by meisnate12** [comment]
btw development here has stalled check out the updated [Plex Meta Manager](https://github.com/meisnate12/Plex-Meta-Manager)

**Comment by AwesomeAustn** [comment]
> btw development here has stalled check out the updated [Plex Meta Manager](https://github.com/meisnate12/Plex-Meta-Manager)

Thanks for the heads up. I'll check it out.
