### ISSUE TITLE
Add "Remove" sync mode

### ISSUE THREAD

**Issue by spauldhaliwal** [mza921/Plex-Auto-Collections#234]
It would be nice to add a "remove" sync option, in addition to sync and append. The reason for this is that there are current issues with how Plex handles items in multiple collections which have different visibility options.

For example, If I have the _Harry Potter Collection_ and it is set to "show collection only" so that it doesn't show the individual items in the library, but only the _Harry Potter Collection_ entry, BUT I also have an _IMDB Top 250 collection_ that is set to "show items and collection", there will be an issue. The issue is that _Harry Potter and the Deathly Hallows: Part 2_ is also in _IMDB Top 250_, and the visibility modes clash.

The result of the above is that in the Library view I will see _The Harry Potter Collection_ item as well as _Harry Potter and the Deathly Hallows: Part 2_ item sitting outside / next to the collection entry.

The workaround for this is pretty weird but it's as follows:

-You set both Harry Potter Collection and IMDB Top 250 to "hide items"
-You then create a new collection called "Force Show", and inside the IMDB Top 250 collection you select any item that **is not** part of another "hidden" collection (Like Hary Potter Collection) and add it to Force Show
-Force Show collection has the "show items" attribute enabled

This is mostly working with your script except for the last step. I have a collection defined and in it, I add all the lists already defined that have the "show items" attribute (such as IMDB Top 250, Criterion Collection, etc) So all the items in these lists are added to their individual lists respectively but also added to the Force Show list. The missing piece here is then removing all the "hide items" collections from the Force Show collection.

Hope this makes sense, took me a few minutes to wrap my head around it myself.

Also, I'm not sure if the list currently executes collection updates/creation in the same order they are defined in the yaml file. I feel like this would be crucial to this feature working since it would need to be executed last.

**Comment by spauldhaliwal** [comment]
Just realized this project is deprecated in favour of Plex-Meta-Manager. I will migrate first to the new script and see if it satisfies the above requirement and then open a ticket there if need be.

**Comment by meisnate12** [comment]
so PMM does not have a specific remove mode like your asking but it can automate your Force Show collection using `plex_collectionless` detailed [here](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Plex-Builders#plex-collectionless) but IMO that method is obsolete and you can accomplish what you want by using `smart_label` collections detailed [here](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Smart-Builders#smart-label)
