### ISSUE TITLE
Could not connect to Radarr

### ISSUE THREAD

**Issue by azra3l2805** [mza921/Plex-Auto-Collections#236]
Hi,
Am trying out the script but am facing the could not connect to Radarr error. 

If I run the script without sudo I get the below error `PermissionError: [Errno 13] Permission denied: '/home/azra3l/Plex-Auto-Collections/config/config.yml'`

If I run the script with sudo I get the below error `Connecting to Radarr...
| Could not connect to Radarr at http://radarr.xyz.in`

**Comment by meisnate12** [comment]
development here has stalled check out the updated [Plex Meta Manager](https://github.com/meisnate12/Plex-Meta-Manager).
