### ISSUE TITLE
Poster no longer being uploaded / set unless using the image server.

### ISSUE THREAD

**Issue by JourneyOver** [mza921/Plex-Auto-Collections#28]
Splitting #27 as requested.

It no longer seems to upload / set the poster when using the `poster` url config settings. Removing the `poster` url settings from the collections and instead use the image server method it sets the poster correctly.

<details>
<summary>old text</summary>

1. Doesn't seem to download images anymore when setting a `poster` under the details section of a collection in the config file. Removing the `poster` and putting the image in the `config/images` location still seems to work, but it'd be great to get the other way to work as well..

</details>

**Comment by burkasaurusrex** [comment]
What was the poster folder path you were using?

**Comment by JourneyOver** [comment]
I dunno if you understand what I mean, I mean when using something like the `Jurassic Park` example:

```
Jurassic Park:
    tmdb-list: https://www.themoviedb.org/collection/328
    details:
        tmdb-summary: 328
        poster: https://i.imgur.com/QMjbyCX.png
```

it doesn't upload / set the poster, but if I was to say take the `poster` bit out and add the poster to the `config\images` folder with the name `Jurassic Park.png` and use the image server it works just fine.

**Comment by louis-lau** [comment]
Same here, with the jurassic park example. No poster is set.

**Comment by burkasaurusrex** [comment]
Ah got it. I see the issue. Seems like this would not have worked for several months?

**Comment by JourneyOver** [comment]
Yea it's been at least a good while now, I can't remember the exact date when I last used this script tbh but I do know it's been a bit.

**Comment by burkasaurusrex** [comment]
@louis-lau and @JourneyOver do you mind giving this branch a try? https://github.com/burkasaurusrex/Plex-Auto-Collections/tree/external-poster-fix

**Comment by JourneyOver** [comment]
Yea that branch seems to be working just fine with the whole external poster stuff now. Now if only I could figure out #27
