### ISSUE TITLE
Feature Request/Bug: Add support for radarr v3

### ISSUE THREAD

**Issue by ExDominatus** [mza921/Plex-Auto-Collections#29]
Currently, the script fails when attempting to add movies via the Radarr v3 API. From what I can tell, there are no major breaking changes to Aphrodite's API that would prevent the "Add Movie" Function from working. Would also appreciate any help if anyone's gotten it to work.

**Comment by burkasaurusrex** [comment]
Sure, looks like a slight URL change from `/api` to `/api/v3`. I'll include an option in the YAML to change the Radarr version.

**Comment by burkasaurusrex** [comment]
@ExDominatus can you give this branch a try? https://github.com/burkasaurusrex/Plex-Auto-Collections/tree/radarr-api-v3

Just add `version: v3` under the `radarr` key in your YAML and it should work.

**Comment by ExDominatus** [comment]
I didn't test your branch, but changing the URL to /api/v3 in radarr_tools does indeed work. I'll test with your branch once my current auto collect finishes (it might be a while unfortunately!).

**Comment by ExDominatus** [comment]
@burkasaurusrex So just tested this, and it worked fine for a list, but failed for another (I'll open another issue, don't think it has anything to with Radarr changes.

Thank you for adding the v3 support!
