### ISSUE TITLE
Trakt API timeout errors

### ISSUE THREAD

**Issue by ExDominatus** [mza921/Plex-Auto-Collections#31]
One of my servers is able to process lists just fine, while one gets ReadTimeoutErrors after hours of processing a trakt list. Can anyone who has everything working shed light on how long it should take to process a Trakt list (given a certain list size)?

`
Attempting to start image server
IMAGE SERVER RUNNING ON http://127.0.0.1:12920/images/
Update Collections from Config? (y/n): y
Updating collection: Kung Fu...
Processing trakt-list: https://trakt.tv/users/bluedfb/lists/kung-fu-classics
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=24)")': /search/tmdb/455610?type=movie
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=24)")': /search/tmdb/455610?type=movie
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out`

**Comment by burkasaurusrex** [comment]
@mza921 any interest in taking a look at this? I haven't spent any time with the Trakt code

@ExDominatus is this a separate issue than #14 ?

**Comment by ExDominatus** [comment]
I believe so, since the previous issue #14 broke all lists for me, which I have not been able to reproduce again. This one, breaks most of them, but I was able to get one list working. For reference, here are the lists:

Server 1: 
Working: https://trakt.tv/users/reto1962/lists/dc-movies
Not working: https://trakt.tv/users/bluedfb/lists/kung-fu-classics
Not working: https://trakt.tv/users/maxwelldeux/lists/101-war-movies-you-must-see-before-you-die

Server 2:
Working: https://trakt.tv/users/bluedfb/lists/kung-fu-classics
Working (but also failed once with same error as in main post): https://trakt.tv/users/maxwelldeux/lists/101-war-movies-you-must-see-before-you-die

I am rerunning a couple other tests to see if it has anything to do with list size. However, it literally takes hours when processing the trakt list. I have sometimes have it be way faster (10-15 minutes), and sometimes takes nearly 8 hours. Is this at all dependent on the CPU/network of the server running autocollections or is it completely reliant on how the trakt API is feeling?

If you have some test cases along with `time`, I could try the same lists.

**Comment by mza921** [comment]
I have seen a similar issue occasionally with my own library against a different Trakt list, but it always seemed to resolve itself when I tried again later. The errors you're seeing suggest it's an issue with the request to the Trakt API flaking out. Have you retried lately?

**Comment by meisnate12** [comment]
can you test this with the new version to see if you still get this issue if not we can close this
