### ISSUE TITLE
New Plex Movie Library Support

### ISSUE THREAD

**Issue by abnersnell** [mza921/Plex-Auto-Collections#33]
This script, especially with Trakt list support, has been working perfectly for me.  Recently I upgraded my Plex Movie library to use the new Plex Movie Agent for matching described here - https://forums.plex.tv/t/introducing-the-new-plex-movie-agent/615989

The script no longer works for the Movie Library while TV Library hums along.  I am guessing an update needs to be made to support the new Plex Movie Library/Agent.   

Thanks again for this script!

**Comment by burkasaurusrex** [comment]
I need to look at the code again, but I'm pretty sure we're going to have to wait on the [PlexAPI](https://github.com/pkkid/python-plexapi) dependency to be updated. There are two different issues about it there:

- https://github.com/pkkid/python-plexapi/issues/534
- https://github.com/pkkid/python-plexapi/issues/557

Both imply waiting until it's out of Plex Pass before implementing it, so it may be a while.

**Comment by pekempy** [comment]
Hey @burkasaurusrex  - it's out of plex pass/beta now, any chance this will be updated? 
pkkid/python-plexapi#557

**Comment by burkasaurusrex** [comment]
Thanks - it looks like the dependency hasn't been updated yet though. Once both of the issues above are closed, we should be good to go.

**Comment by burkasaurusrex** [comment]
Seems like it might be a while until the new matching is supported. We should consider adding a check to see if the library has been upgraded or not and notify the user. We'll probably need to do the check eventually anyways to support upgraded and non-upgraded libraries.

**Comment by meisnate12** [comment]
we should be able to get support working once [pkkid/python-plexapi#562](https://github.com/pkkid/python-plexapi/pull/562) goes through as detailed [here](https://github.com/pkkid/python-plexapi/issues/557#issuecomment-707778230)

**Comment by burkasaurusrex** [comment]
@mza921 do you mind pinning this issue? Might cut down on some other issues

**Comment by mza921** [comment]
There's something available to test in the [new-movie-agent](https://github.com/mza921/Plex-Auto-Collections/tree/new-movie-agent) branch.
- Only supports Trakt/IMDB (doesn't work with TMDB related lists yet)
- Initial run might be slow as it creates a cache for the IMDB ID -> Plex Agent ID mapping

**Comment by JourneyOver** [comment]
Looks like in the past 5 hours they have added support for TMDB. So it should now support all three lists.
