### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by vitadome** [mza921/Plex-Auto-Collections#39]
Hello,
My apologies for posting here but could someone assist / point me in the right direction with the error I'm receiving while trying to run the collection tool.

Traceback (most recent call last):
  File "plex_auto_collections.py", line 202, in <module>
    plex = Plex(config_path)
  File "C:\Users\vitdom01\Plex\Plex-Auto-Collections-master\Plex-Auto-Collections-master\app\config_tools.py", line 53, in __init__
    config = Config(config_path).plex
  File "C:\Users\vitdom01\Plex\Plex-Auto-Collections-master\Plex-Auto-Collections-master\app\config_tools.py", line 25, in __init__
    with open(self.config_path, 'rt', encoding='utf-8') as yml:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yml'

**Comment by burkasaurusrex** [comment]
It looks like it's not finding your `config.yml` file. If you've updated the template included in the repo, make sure to rename it from `config.yml.template` to just `config.yml` and put it in the `config` folder alongside the `app` folder.

**Comment by burkasaurusrex** [comment]
Ah, apologies, I forgot to push a fix to autodetect where the `config.yml` is. For now, you should be able to run it with `python plex_auto_collections.py -c <path_to_config>` for now.

**Comment by vitadome** [comment]
I'm still experiencing issues and not sure what I'm doing wrong.  Could someone assist please?

C:\Plex-Auto-Collections\app>python plex_auto_collections.py --config-path C:\Plex-Auto-Collections\config\config.yml

|===================================================================================================|
|     ___  _               _         _           ___       _  _           _    _                    |
|    | _ \| | ___ __ __   /_\  _  _ | |_  ___   / __| ___ | || | ___  __ | |_ (_) ___  _ _   ___    |
|    |  _/| |/ -_)\ \ /  / _ \| || ||  _|/ _ \ | (__ / _ \| || |/ -_)/ _||  _|| |/ _ \| ' \ (_-<    |
|    |_|  |_|\___|/_\_\ /_/ \_\\_,_| \__|\___/  \___|\___/|_||_|\___|\__| \__||_|\___/|_||_|/__/    |
|                                                                                                   |
|===================================================================================================|
| Locating config...
| Using C:\Plex-Auto-Collections\config\config.yml as config
|===================================================================================================|
| Connecting to plex...
| plex connection scuccessful
|===================================================================================================|
| Connecting to tmdb...
| tmdb connection scuccessful
|===================================================================================================|
| Connecting to trakt...
| Config Error: trakt sub-attribute client_id is blank
| trakt connection failed
|===================================================================================================|
| Connecting to radarr...
| Config Error: radarr sub-attribute version not found using v2 as default
| Config Error: radarr sub-attribute token is blank
| radarr connection failed
|===================================================================================================|
| Locating image_server...
Traceback (most recent call last):
  File "plex_auto_collections.py", line 471, in <module>
    config = Config(config_path)
  File "C:\Plex-Auto-Collections\app\config_tools.py", line 85, in __init__
    ImageServer(config_path)
  File "C:\Plex-Auto-Collections\app\config_tools.py", line 242, in __init__
    checkPath("poster_directory", self.poster, "image_directory")
  File "C:\Plex-Auto-Collections\app\config_tools.py", line 239, in checkPath
    v = os.path.abspath(value)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 527, in abspath
    return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType

C:\Plex-Auto-Collections\app>

**Comment by meisnate12** [comment]
download the latest update 2.0.0 it should fix this problem
