### ISSUE TITLE
To do: "Discover" and "General Feature" from TMDb API

### ISSUE THREAD

**Issue by burkasaurusrex** [mza921/Plex-Auto-Collections#41]
see vladimir-tutin/Plex-Auto-Collections#15

**Comment by meisnate12** [comment]
Posting these here for future reference 
[Movie Commands](https://developers.themoviedb.org/3/discover/movie-discover)
[TV Commands](https://developers.themoviedb.org/3/discover/tv-discover)

**Comment by burkasaurusrex** [comment]
It probably makes sense to just use the `discover` endpoint, but there are a bunch of other seemingly redundant endpoints like [Get Trending](https://developers.themoviedb.org/3/trending/get-trending) or [Get Popular](https://developers.themoviedb.org/3/movies/get-popular-movies). I assume the different endpoint would return the same data but not sure.

**Comment by meisnate12** [comment]
So I'm thinking of working on adding this next I was just gonna start with discover and see where it takes me

**Comment by meisnate12** [comment]
this can be closed
