### ISSUE TITLE
To do: Create setting for other collection-level metadata

### ISSUE THREAD

**Issue by meisnate12** [mza921/Plex-Auto-Collections#43]
It would be amazing if you could set the background image for collections in basically the exact same way you can for the poster images. maybe a different folder for local background assets vs posters or have the program match folder name inside the assets folder and the have a poster.* and/or background.* file in there that it picks up.

Edit: In addition to the background settings and sort title setting (which I saw you already had a ticket for) I think it would be beneficial to also add a setting for content rating, and if possible be able to specify in the YXML the collection mode and collection order that are under advance settings.

**Comment by meisnate12** [comment]
ok so I went in and figured out how to add all these things you have to update the plex API to 4.1.1 from 4.0.0 for these to work

If this code is put into config_tools.py at line 261 youll have these new options under details 
      titleSort: PixarSort
      contentRating: E
      collectionMode: showItems
      collectionSort: alpha
      background: <URL>

if you leave off background it will look in your image server form the Collection Name + "-background" ie. Pixar-background.png should be your file name for the background. I think the plex API should be able to add posters and backgrounds from a file path instead of having to create an image server, but I didn't wanna change too much and this works.

collectionMode has these options
      default (Library default) 
      hide (Hide Collection) 
      hideItems (Hide Items in this Collection) 
      showItems (Show this Collection and its Items)

collectionMode has these options
      realease (Order Collection by release dates) 
      alpha (Order Collection Alphabetically)


`
            item = plex.Server.fetchItem(rkey)

            # Handle collection contentRating
            if "contentRating" in collections[c]["details"]:
                edits = {'contentRating.value': collections[c]["details"]["contentRating"], 'contentRating.locked': 1}
                item.edit(**edits)
                item.reload()

            # Handle collection titleSort
            if "titleSort" in collections[c]["details"]:
                edits = {'titleSort.value': collections[c]["details"]["titleSort"], 'titleSort.locked': 1}
                item.edit(**edits)
                item.reload()

            # Handle collection collectionMode
            if "collectionMode" in collections[c]["details"]:
                collectionMode = collections[c]["details"]["collectionMode"]
                if collectionMode in ('default', 'hide', 'hideItems', 'showItems'):
                    item.modeUpdate(mode=collectionMode)
                else:
                    print("collectionMode Invalid\ndefault (Library default)\nhide (Hide Collection)\nhideItems (Hide Items in this Collection)\nshowItems (Show this Collection and its Items)\n")

            # Handle collection collectionSort
            if "collectionSort" in collections[c]["details"]:
                collectionSort = collections[c]["details"]["collectionSort"]
                if collectionSort in ('release', 'alpha'):
                    item.sortUpdate(sort=collectionSort)
                else:
                    print("collectionSort Invalid\nrelease (Order Collection by release dates)\nalpha (Order Collection Alphabetically)\n")

            # Handle collection backgrounds
            background = None
            if "background" in collections[c]["details"]:
                background = collections[c]["details"]["background"]
            else:
                # Try to pull image from image_server.
                # To do: this should skip if it's run without the image server
                # To do: this only runs if 'details' key is set - might make sense to run regardless
                # Setup connection to image_server
                config_client = ImageServer(config_path, "client")

                # Url encode collection name
                c_name = urllib.parse.quote(c, safe='')

                # Create local url to where image would be if exists
                local_background_url = "http://" + config_client.host + ":" + str(config_client.port) + "/images/" + c_name + "-background"

                # Test local url
                response = requests.head(local_background_url)
                if response.status_code < 400:
                    background = local_background_url

            if background:
                item.uploadArt(url=background)
`

**Comment by mza921** [comment]
Great idea. I will check it out.

**Comment by burkasaurusrex** [comment]
Cool. I'll create a pull request. Agreed that it makes sense to get rid of the image server now that the `PlexAPI` package supports editing collections.
