### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by b101marc** [mza921/Plex-Auto-Collections#48]
Getting the following when attempting to run the script using a trakt list:

`Traceback (most recent call last):
  File "plex_auto_collections.py", line 378, in <module>
    update_from_config(config_path, plex, True)
  File "plex_auto_collections.py", line 54, in update_from_config
    missing = add_to_collection(config_path, plex, m, v, c, subfilters)
  File "/app/plex_tools.py", line 135, in add_to_collection
    movies, missing = trakt_tools.trakt_get_movies(config_path, plex, value)
  File "/app/trakt_tools.py", line 14, in trakt_get_movies
    title_ids = [m.pk[1] for m in trakt_list_items if isinstance(m, trakt.objects.movie.Movie)]
TypeError: 'NoneType' object is not iterable`

**Comment by burkasaurusrex** [comment]
I've come across this when my Trakt token expired. Maybe try erasing the values for the keys under `authorization` in the `trakt` yaml and reauthenticate?

**Comment by meisnate12** [comment]
can you test this with the new version to see if you still get this issue if not we can close this

**Comment by b101marc** [comment]
Trying to run the new version but running in to this error.

`Connecting to Trakt...
| Stored Authorization Failed
| Run without --update/-u to configure Trakt
| Trakt Connection Failed`

I've confirmed that my trakt id and secret are correct.

**Comment by meisnate12** [comment]
it has to open the web browser to authenticate your going to have to run the program on a computer and connect to trakt and then once it's successful you can copy the whole trakt section in the config to your one on the server and it should work. Unforutenly it's currently impossible to do the authentication while running it in -u mode.

**Comment by b101marc** [comment]
I was able to get Trakt to authorize, however when running `python3 -d plex_auto_collections.py` if I enter the lists submenu and input any type of list I get a bar url error. Some example of url's I have used are:

https://trakt.tv/users/justin/lists/imdb-top-rated-tv-shows?sort=rank,asc
https://www.imdb.com/list/ls094401631/
https://thetvdb.com/lists/arrowverse

**Comment by meisnate12** [comment]
Can you post the error trace?

**Comment by b101marc** [comment]
I found the error, a minor spelling mistake in the config that didn't give me an error. This can be closed.
