### ISSUE TITLE
To do: Add to (and remove from) Collection based on configurable release date

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#54]
Think "New Releases" collection.
See similar: https://github.com/blacktwin/JBOPS/blob/master/utility/recently_added_collection.py

**Comment by burkasaurusrex** [comment]
Cool idea. This is probably quickest to develop leveraging Tautulli if that works? Depends on #53

**Comment by meisnate12** [comment]
Tautulli can do a recently added list but it would be more like the most recent 50 movies, not movies that have been added in the last 60 days

**Comment by meisnate12** [comment]
and now that i think about it while its not a collection plex already has recently added but we may be able to do it by a date like in the program above still

**Comment by bigdork** [comment]
The suggested script is named "recently added" but it's really "new releases." They did it with Tautulli but both Plex and Tautulli have access to the movie/show "release date." I currently curate my "New Release" collection manually every month, but would be a useful feature in this script.

**Comment by meisnate12** [comment]
if this has been added can we close this?
