### ISSUE TITLE
To do: Add README section detailing use of quotes

### ISSUE THREAD

**Issue by meisnate12** [mza921/Plex-Auto-Collections#56]
maybe we should have a section of the README dedicated to showing people examples of when to use or not to use quotes and let them know some of the common special characters that would require the use of quotes.

**Comment by BlueSkillZ99** [comment]
That would be a really good idea.  I am struggling to put a hash # in front of Collection names and sort titles. The script seems to think that it is a comment. I tried double and single quotes around the hash and the whole collection name, but nothing seems to work.
