### ISSUE TITLE
Support Request -- Still Experiencing issues

### ISSUE THREAD

**Issue by vitadome** [mza921/Plex-Auto-Collections#57]
**I'm still experiencing issues and not sure what I'm doing wrong. Could someone assist please?**

C:\Plex-Auto-Collections\app>python plex_auto_collections.py --config-path C:\Plex-Auto-Collections\config\config.yml

|===================================================================================================|
| ___ _ _ _ ___ _ _ _ _ |
| | _ | | ___ __ __ /\ _ _ | | ___ / | ___ | || | ___ __ | | (_) ___ _ _ ___ |
| | /| |/ -)\ \ / / _ | || || |/ _ \ | ( / _ | || |/ -)/ || || |/ _ | ' \ (-< |
| || ||_|/_\ // _\,| __|_/ _|_/||||_|_| _||_|_/||||/__/ |
| |
|===================================================================================================|
| Locating config...
| Using C:\Plex-Auto-Collections\config\config.yml as config
|===================================================================================================|
| Connecting to plex...
| plex connection scuccessful
|===================================================================================================|
| Connecting to tmdb...
| tmdb connection scuccessful
|===================================================================================================|
| Connecting to trakt...
| Config Error: trakt sub-attribute client_id is blank
| trakt connection failed
|===================================================================================================|
| Connecting to radarr...
| Config Error: radarr sub-attribute version not found using v2 as default
| Config Error: radarr sub-attribute token is blank
| radarr connection failed
|===================================================================================================|
| Locating image_server...
Traceback (most recent call last):
File "plex_auto_collections.py", line 471, in
config = Config(config_path)
File "C:\Plex-Auto-Collections\app\config_tools.py", line 85, in init
ImageServer(config_path)
File "C:\Plex-Auto-Collections\app\config_tools.py", line 242, in init
checkPath("poster_directory", self.poster, "image_directory")
File "C:\Plex-Auto-Collections\app\config_tools.py", line 239, in checkPath
v = os.path.abspath(value)
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 527, in abspath
return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType

C:\Plex-Auto-Collections\app>

**Comment by meisnate12** [comment]
can you post your config file

**Comment by vitadome** [comment]
collections:
  Back to the Future:
    imdb-list: https://www.imdb.com/list/ls081648619/
  Harry Potter:
    imdb-list: https://www.imdb.com/list/ls081862830/
  Indiana Jones:
    imdb-list: https://www.imdb.com/list/ls083085242/
  Jason Bourne:
    imdb-list: https://www.imdb.com/list/ls081920213/
  Jurassic Park:
    imdb-list: https://www.imdb.com/list/ls083087810/
  Star Wars:
    imdb-list: https://www.imdb.com/list/ls083086725/
  Taken:
    imdb-list: https://www.imdb.com/list/ls083556973/
  The Godfather:
    imdb-list: https://www.imdb.com/list/ls081230674/
  The Hobbit & Lord of the Rings:
    imdb-list: https://www.imdb.com/list/ls081864486/
  The Hunger Games:
    imdb-list: https://www.imdb.com/list/ls081868767/
plex:
  library: Movies
  library_type: movie ### 'movie' or 'show' ###
  token: a4YzyxxxxxxxxxxTxe7C
  url: http://xxx.xxx.xx.xxx:xxxxx
radarr:
  url: http://192.168.1.5:7878/radarr/
  token: ###########################
  quality_profile_id: 4
  root_folder_path: /mnt/user/PlexMedia/movies
  add_movie: false
  search_movie: false
tmdb:
  apikey: 7dd596xxxxxxxxxx4df82171d9c48960
  language: en
trakt:
  client_id: ###########################
  client_secret: ###########################
  # Below is filled in automatically when the script is run
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:
image_server:
  poster_directory: ../config/posters
  background_directory: ../config/backgrounds
  image_directory: ../config/images

**Comment by meisnate12** [comment]
i think theres a bug thats going to be fixed in a release that should be coming in the next couple of days but for now try deleting the whole image_server section and rerun and see if that works for you

**Comment by vitadome** [comment]
I think I'm getting closer -- I removed the image_server lines as suggested but now receive the following error:

Enter list type IMDb(i) TMDb(t) Trakt(k): i
| Enter IMDb List URL: https://www.imdb.com/list/ls083709265/
| Enter collection name: M Night Shyamalan
| Processing IMDb List: https://www.imdb.com/list/ls083709265/
Traceback (most recent call last):
  File "plex_auto_collections.py", line 516, in <module>
    missing = add_to_collection(config_path, plex, method, url, c_name)
  File "C:\Plex-Auto-Collections\app\plex_tools.py", line 135, in add_to_collection
    if TMDB.valid:                  movies, missing = imdb_tools.imdb_get_movies(config_path, plex, value)
  File "C:\Plex-Auto-Collections\app\imdb_tools.py", line 33, in imdb_get_movies
    imdb_id = tmdbapi.imdb_id
AttributeError: 'AsObj' object has no attribute 'imdb_id'

**Comment by meisnate12** [comment]
try updating to 2.0.0 that we just released and see if that helps im pretty sure ive fixed that error in the 2.0.0 release

**Comment by vitadome** [comment]
Trying to install 2.0.0 but extract keeps getting hung up on docker image file.

**Comment by meisnate12** [comment]
Ahh I'm not sure the docker has been updated yet I'm sure it will be soon

**Comment by burkasaurusrex** [comment]
The docker image has been updated. Can you change your `image_server` config to the following and try again?
```yaml
image_server:
  poster_directory: /config/posters
  background_directory: /config/backgrounds
  image_directory: /config/images
```

**Comment by vitadome** [comment]
Uncompressing 2.0 version is still locking up my system.
 - I removed the .dockerignore file
 - I also removed the image_servers from the config.yml

With those changes I was able to uncompress and launch/use the tool without issue.

**Comment by meisnate12** [comment]
can you try updating to 2.1.1 and see if you're still having issues

**Comment by vitadome** [comment]
This worked without any issues.  Thank you!
