### ISSUE TITLE
New in v2.0.0 - Incorrect TMDB info for people

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#60]
Snippet from config, but it's not just Chappelle:
```
Actor Dave Chappelle:
    sort_title: -5 Actor Dave Chappelle
    actors: Dave Chappelle
    #tmdb_id: 4169
    tmdb_summary: 4169
    tmdb_poster: 4169
    collection_order: release
```

When running, the incorrect poster (for Chappelle) is loaded:
`| Detail: poster updated to [url] https://image.tmdb.org/t/p/original/m2iVkJPxDrrink7NiE412nFBMQj.jpg`

This is the incorrect poser, as shown. 
<img width="626" alt="Screen Shot 2020-10-25 at 9 09 56 PM" src="https://user-images.githubusercontent.com/58086116/97124460-914e4300-1706-11eb-8fc1-0502e9197a96.png">

The URL to the proper poster (Chappelle) should be _https://image.tmdb.org/t/p/original/qrJzigQLQ7FwrzYBLeDwvuPN63t.jpg_
 
Also, not sure if it is known but tmbd_id still doesn't work :(

**Comment by bigdork** [comment]
Note, this was working properly pre-v2.0.0.0.

**Comment by meisnate12** [comment]
ill update the readme but tmbd_id isnt supposed to work with actors just with collections and movies i could add a tmdb_actor attribute that could do both summary and poster as for the error give me a little bit im gonna try and figure out whats going on

**Comment by meisnate12** [comment]
so its finding the tmdb movie 4169 which is the intended use since 2.0.0 what I'll add to 2.1.0 is `tmdb_actor` and when you specify 4169 there it will update everythin correctly

**Comment by bigdork** [comment]
> so its finding the tmdb movie 4169 which is the intended use since 2.0.0 what I'll add to 2.1.0 is `tmdb_actor` and when you specify 4169 there it will update everythin correctly 

Ack, I noted Chappell because that's what is shown (now, incorrectly) in the readme.

**Comment by meisnate12** [comment]
its a change in tmdb_summary and tmdb_poster that allows their queries to be more accurate but it lost the weird way they were doing peoples posters. I've got this almost all ready to go in 2.1 so youll see the fix coming soon.
