### ISSUE TITLE
Support Trakt trending movies/shows list

### ISSUE THREAD

**Issue by mza921** [mza921/Plex-Auto-Collections#61]
- Generate a collection from https://trakt.tv/movies/trending
- User-defined size
- Possibly support filters? (e.g. Top 10 Trending Sci-Fi)

**Comment by meisnate12** [comment]
this might be easier if we switch what trakt dependency were using, [PyTrakt](https://github.com/moogar0880/PyTrakt) looks like a much more powerful dependency then the one were currently using

**Comment by mza921** [comment]
I have it mostly working. I'll follow up your pull request. The syntax will be:
```
collections:
  Trakt Trending Movies:
    trakt_trending: <list_size> # default is 10
```

I tried PyTrakt early on, but settled on trakt.py since it had all the functionality I needed.
