### ISSUE TITLE
Bug: New in v2.0.0, Shows no longer match, "unknown filter category"

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#63]
Genre (genres) worked prior to v2.0.0.
Studio matching did not work prior to v2.0.0, and still does not but now errors with the same "unknown filter categroy"

Config:
```
  Quibi:
    studio: Quibi
    sort_title: -3 Quibi
    summary: A collection of TV Shows from the Quibi streaming service
    collection_order: alpha
  Anime:
    genres: Anime
    sort_title: -2 Anime
    summary: A collection of TV shows from the Anime genre
    collection_order: alpha
  Comedy:
    genres: Comedy
    sort_title: -2 Comedy
    summary: A collection of TV shows from the Comedy genre
    collection_order: alpha
```

Output:
```
|===================================================================================================|
|
| Updating collection: Quibi...
| Sync Mode: append
|
| Processing studio: Quibi
**Unknown filter category: studio**
|
| Processing collection_order: alpha
|
| Detail: sort_title updated to -3 Quibi
| Detail: summary updated to "A collection of TV Shows from the Quibi streaming service"
|
|===================================================================================================|
|
| Updating collection: Anime...
| Sync Mode: append
|
| Processing genre: Anime
**Unknown filter category: genres**
|
| Processing collection_order: alpha
|
| Detail: sort_title updated to -2 Anime
| Detail: summary updated to "A collection of TV shows from the Anime genre"
|
|===================================================================================================|
|
| Updating collection: Comedy...
| Sync Mode: append
|
| Processing genre: Comedy
**Unknown filter category: genres**
|
| Processing collection_order: alpha
|
| Detail: sort_title updated to -2 Comedy
| Detail: summary updated to "A collection of TV shows from the Comedy genre"
|
|===================================================================================================|
```

**Comment by mza921** [comment]
For shows, can you try using `genre` instead?

**Comment by meisnate12** [comment]
if it is just genres to genre for shows we could add a check for that

**Comment by burkasaurusrex** [comment]
The README is pretty vague. Not sure how the code is written now, but prior versions was very flexible (probably too flexible). We should probably just explicitly support the following?

- studio (str) – Studio that created movie (Di Bonaventura Pictures; 21 Laps Entertainment).
- year (int) – Year movie was released.
- countries (List<Country>) – List of countries objects.
- directors (List<Director>) – List of director objects.
- genres (List<Genre>) – List of genre objects.
- producers (List<Producer>) – List of producers objects.
- writers (List<Writer>) – List of writers objects.
- actors / roles (List<Role>) – List of role objects.

**Comment by meisnate12** [comment]
this part of the code shouldnt have changed it basically just asks if there is a plex filter 

`method` is `genre`, `year`, etc and `value` is whatever its set to ie. `Action` or `1990`

this is the code for movie which also has a catch and to try again without the s if there is one. 
This catch is not implemented for shows. I've fixed this in the 2.1.0 release I'm putting together
 
```
if (method in Movie.__doc__ or hasattr(Movie, method)):
            try:
                movies = plex.Library.search(**{method: value})
            except PlexExceptions.BadRequest:
                # If last character is "s" remove it and try again
                if method[-1:] == "s":
                    movies = plex.Library.search(**{method[:-1]: value})
                    movies = [m.ratingKey for m in movies if movies]
```

**Comment by meisnate12** [comment]
but i do agree limiting this and making the README more detailed about it would be good

**Comment by burkasaurusrex** [comment]
What do you think about creating a `dict` like:

```python
methods = {
    "studio": "studio",
    "year": "year",
    "country": "countries",
    "director": "directors",
    "genre": "genres",
    "producer": "producers",
    "writer": "writers",
    "actor": "roles"
}
```

That way it supports weird pluralizations (countries vs country) and it's simpler for the user since all the methods will be singular?

**Comment by meisnate12** [comment]
Yea I think we should but looking at the filters I would just also add content rating to your list we also need to look at how subfilters work as well because I would want them to have the same restrictions as filters

**Comment by meisnate12** [comment]
after some more digging we can actually do alot with the search feature detailed [here](https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.search)

**Comment by meisnate12** [comment]
ok after some trial and error I've determined that theses all work as movie searches

`actor`, `country`, `decade`, `director`, `genre`, `studio`, `year`, `writer`

and these work as tv searches

`genre`, `network`, `year`

As for subfilters, these are done differently so there are slightly different options for movies we can use

`actors`, `contentRating`, `countries`, `directors`, `genres`, `studio`, `year`, `writers`

and for tv we can use

`actors`, `contentRating`, `genres`, `studio`, `year`

as you can see some of the names would have to be changed to keep them consistent like `contentRating` to `content_rating` and `network` would be `studio`, which is how its labeled in Plex. We would just have to change them back to the right thing before we actually use it. Some of the subfilters are the pluralized when the regular filter would not be. 

We can do the overall filter using `contentRating` as well but we're already using the attribute `content_rating` to edit the content rating so one of those names would have to be different or we could use a category like filters and then have all these under said category.

```
collections:
    G Rated:
        Filters:
            content_rating
```

something like that or we put the edits back under `details` but i wanna avoid that since we just got rid of `details`

**Comment by burkasaurusrex** [comment]
This is really good work - this looks right to me. @mza921 any thoughts?

So how does the logic work between filters and subfilters then? `(filter || filter || filter) && (subfilter && subfilter && subfilter)`? And you can use the same filter as a filter and subfilter simultaneously?

**Comment by mza921** [comment]
I'm all for normalizing the filter names. I don't think there's a distinction between `filter` and `subfilter` in the `plexapi` module, it's just an extra option created in the original repo. I think you're right about the logic between filters/subfilters. I'd love to see support for logical operators, but would need to figure out how to present it in YAML and pass it to `plexapi`. Or maybe incorporate how Tautulli does custom logic within notification agents (e.g. `{1} and ({2} or {3}`).

**Comment by meisnate12** [comment]
its more like `(filter && subfilter && subfilter) || (filter && subfilter && subfilter) || (filter && subfilter && subfilter)` which is logically equilvant to `(filter || filter || filter) && (subfilter && subfilter && subfilter)`

and @mza921 there's actually a huge difference in the way this script handles filters vs subfilters for filters. For filters, it uses the `plexapi`'s [Library Section search](https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.search) but after that search, the script loops through the rating keys of every movie/show found in the section search and then loops through each subfilter. For each subfilter, the script runs `getattr(current_m, method)` where `current_m = get_movie(plex, rating_key)` and method is a string method name for the subfilter. Then it checks to make sure that the movie/show has your particular attribute and if it does it lets it get added otherwise it fails and isn't added.

filters = [LibrarySection.search](https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.search) 

subfilters = Use attributes of the `plexapi` [Movie](https://python-plexapi.readthedocs.io/en/latest/modules/video.html#plexapi.video.Movie) Object or [Show](https://python-plexapi.readthedocs.io/en/latest/modules/video.html#plexapi.video.Show) Object to manually loop through and check each one

I haven't mentioned this here yet but the [LibrarySection.search](https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.search) can take `method!` as a logically not so I managed to make subfilters act the same way and I'm also working on adding `rating.lte` and `rating.gte` for rating less then and greater then I think the `.lte` and `.gte` are good to use since if we add tmdb discover we would also use that same syntax there.

**Comment by mza921** [comment]
Good info. I like the notation used in the [operator](https://docs.python.org/3/library/operator.html) module, but no reason we can't support multiple notations. For your last example and using your proposed list of subfilters, 
```
collections
    Adam Sandler Good Romantic Comedies:
        genre.and: 
        - Comedy
        - Romance
        subfilters:
            actor: Adam Sandler
            rating.ge: 7
```
On the backend, the `.and` could trigger the script to build two lists of `genre` results and perform an intersection.

**Comment by bigdork** [comment]
Circling back to the original issue - correcting "genres" to "genre" worked, but trying to collect by either "studio" or "network" or "networks" still produces no results (and no error) - is this expected?

Config snippet:
```
  Quibi:
    sync_mode: append
    collection_order: alpha
    sort_title: -3 Quibi
    summary: A collection of TV Shows from the Quibi streaming service
    network: Quibi
    networks: Quibi
    studio: Quibi
    studios: Quibi
```

Output snippet:
```
| Updating collection: Quibi...
| Sync Mode: append
|
| Processing collection_order: alpha
|
| Processing network: Quibi
|
| Processing network: Quibi
|
| Processing studio: Quibi
|
| Detail: sort_title updated to -3 Quibi
| Detail: summary updated to "A collection of TV Shows from the Quibi streaming service"
```

**Comment by meisnate12** [comment]
i havent submitted the pull request yet by try my branch and see if it fixes your problem you can get it [here](https://github.com/meisnate12/Plex-Auto-Collections) im going to be pushing this to @mza921 repo shortly but id love to know if it fixes your problem first

**Comment by meisnate12** [comment]
btw `collection_order` is wrong it should be `collection_sort`

**Comment by meisnate12** [comment]
and now i see the Readme has order for some reason ill updated that as well

**Comment by meisnate12** [comment]
im going to update the code to look for `collection_order` since that is what plex calls it

**Comment by meisnate12** [comment]
ok so looking at another problem I started doing more testing. the correct input is network for shows but it does not work the plexAPI library has a bug I have a support ticket in now with them so hopefully, they will figure out what's wrong

**Comment by bigdork** [comment]
@meisnate12 Unfortunately, I have not had the opportunity to test your branch. I am excited to use this feature when the bugs are worked out, though. My mother specifically requested "channels" (collections) so she can find this CBS show and that HBO show, and with 6400 TV shows it's quite a chore to setup and maintain the collections.

**Comment by meisnate12** [comment]
@bigdork if you get a chance try and test my branch you seem to have a much more extensive test file then i do at the moment it would really help me catch some bugs before we launch the new version

**Comment by bigdork** [comment]
@meisnate12 

I cloned your branch, pip'd the requirements file, copied in some config, but no go. :(
It is after 1am and I'm tired, maybe I screwed something up?

Config:
```
  Hulu:
    sort_title: -3 Hulu
    summary: A collection of original TV Shows from the Hulu streaming service
    sync_mode: append
    collection_order: alpha
    network: Hulu
```

Output:
```
~/Plex-Auto-Collections$ python3 app/plex_auto_collections.py -c /home/user/Plex-Auto-Collections/config/config.tv.yml -u

|===================================================================================================|
|     ___  _               _         _           ___       _  _           _    _                    |
|    | _ \| | ___ __ __   /_\  _  _ | |_  ___   / __| ___ | || | ___  __ | |_ (_) ___  _ _   ___    |
|    |  _/| |/ -_)\ \ /  / _ \| || ||  _|/ _ \ | (__ / _ \| || |/ -_)/ _||  _|| |/ _ \| ' \ (_-<    |
|    |_|  |_|\___|/_\_\ /_/ \_\\_,_| \__|\___/  \___|\___/|_||_|\___|\__| \__||_|\___/|_||_|/__/    |
|                                                                                                   |
|===================================================================================================|
| Version 2.3.0
| Locating config...
| Using /home/user/Plex-Auto-Collections/config/config.tv.yml as config
|===================================================================================================|
| Connecting to Plex...
| Plex Connection Successful
|===================================================================================================|
| Connecting to TMDb...
| TMDb Connection Successful
|===================================================================================================|
| Connecting to tautulli...
| tautulli connection scuccessful
|===================================================================================================|
| Connecting to Trakt...
| Trakt Connection Successful
|===================================================================================================|
| radarr attribute not found
|===================================================================================================|
| image_server attribute not found
|===================================================================================================|
|
| Running collection update press Ctrl+C to abort at anytime
| 
|===================================================================================================|
|
| Updating collection: Hulu...
| Sync Mode: append
| Config Warning: network attribute will run as studio
| 
| Processing plex_search: ('studio', ['Hulu'])
Traceback (most recent call last):
  File "app/plex_auto_collections.py", line 784, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "app/plex_auto_collections.py", line 415, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/home/user/Plex-Auto-Collections/app/plex_tools.py", line 179, in add_to_collection
    shows = search_plex()
  File "/home/user/Plex-Auto-Collections/app/plex_tools.py", line 128, in search_plex
    search_list = attr_pair[1]
IndexError: list index out of range
```

Output shows successful Plex connection, but fails during Plex search.
I tried `network:`, `networks:`, `studio:`, and `studios:` but no joy.
I tried assorted networks (Netflix, Disney+, etc) but also no love.

**Comment by meisnate12** [comment]
yup thats a bug ill get it fixed and upload a fix by morning so get some sleep lol

**Comment by meisnate12** [comment]
should all be fixed if you wanna give it another go.

**Comment by bigdork** [comment]
Can confirm `studio:` works properly in your branch!

**Comment by bigdork** [comment]
I just noticed 2.4.1 was pushed, I'll be checking out all these filters soon too. Thanks everyone for your hard work!
