### ISSUE TITLE
How would manual collection editing work along the external service sync?

### ISSUE THREAD

**Issue by enchained** [mza921/Plex-Auto-Collections#69]
Hi. I have a small family server, and want to figure out how to track things best, i.e. how to know if any of the users still want that movie/series, or I can delete it. I thought about the collections, this way the users see a collection with their nickname, and for any item they see if it belongs to the collection, and they see whether they're the only one left who needs the item. The only downside is that only I can edit collections, and I have to ask everyone about everything frequently. So I thought of looking for a bot for it, or at least an example of how to work with a collection through an api, but I couldn't find it. But instead I found this amazing tool, and plan to try it out soon. However, first I need to know how it could work with sync. I'm planning to make my users use IMDb or Trakt apps watchlists. For them to be able to edit the collections on Plex end, I suppose I need to use the **sync**, and not the **append** type.

1. Would I be able to import a specific existing collection to the IMDb/Trakt watchlist beforehand, or is it one-way sync?
2. If the user deletes something on their third-party side, and it was initially manually added on Plex side, will it be deleted on sync? Or does sync delete only items that were initially added by sync?
3. Can you sync episodes via IMDb or Trakt? And is there any difference between the syncing capabilities of those two? I'm trying to choose one here.

**Comment by meisnate12** [comment]
1. Are you asking if the script can update the IMDB/Trakt playlist with items you manually add to the collection in plex? If so, then no this script is not designed to update those playlists. It just edits your plex library.
2. sync will remove anything in the collection that is not in the associated lists regardless of how it originally got there.
3. You cant really sync episodes at all if you want something like that you would probably want to use playlists not collections. Collections can't hold individual episodes like playlists can

**Comment by enchained** [comment]
Thanks for answering!

1. Yes, I was asking about that. It's ok if it doesn't, I was just wondering. 
2. So, if there is pre-existing manual collection in Plex, and the user adds some items to the IMDB, and then I sync his IMDB list to the collection, all pre-existing items that arent on IMDB list will be removed? I guess in that case I should give all such collection control to the users completely (or maybe find some of the list services have collaborative list options)
3. The episodes aren't really needed for me, but I was curious in theory since they can be added to the IMDB/Trakt watchlist by mistake or on purpose. What will happen then? Skip or it will be added as a whole Show?

**Comment by meisnate12** [comment]
2. if you use mode append it will only add new items to the collection but then it will no longer remove any either.
3. i hope it would skip but it might just blow up ill test this later and if it does blow up i can add a check to prevent this in a future release

**Comment by meisnate12** [comment]
@mza921 i think we can close this
