### ISSUE TITLE
Read timeouts - able to modify?

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#74]
I have a massive Plex library and I keep getting timeouts, so the script never really completes.
Is there anyway to modify the timeout limit?
Alternatively, is it possible to catch this error, pause for 10s or so, and continue instead of crashing out?

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/usr/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='plex.domain.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 646, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 113, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, subfilters)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 179, in add_to_collection
    current_m = get_movie(plex, rk)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 18, in get_movie
    return plex.Server.fetchItem(data)
  File "/home/user/.local/lib/python3.6/site-packages/plexapi/base.py", line 139, in fetchItem
    for elem in self._server.query(ekey):
  File "/home/user/.local/lib/python3.6/site-packages/plexapi/server.py", line 440, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='plex.domain.com', port=443): Read timed out. (read timeout=30)
```

**Comment by burkasaurusrex** [comment]
Does the script fail on the same collection every time or is it random?

I've only really tested this on Python 3.7+, looks like this might be using Python 3.6. I think we've had this error before and it ended up being a dependency issue. Do you mind making sure the dependencies are up-to-date with something like `pip install --upgrade -r requirements.txt`?

How long do Plex searches usually take to return in the web UI? The timeout default is 30 seconds, but it looks like it can be adjusted: https://github.com/pkkid/python-plexapi/blob/master/docs/configuration.rst . If Plex's web UI returns searches in <30 seconds, the problem probably may not be related to library size unless either machine is way underpowered.

Lastly, it looks like the script is trying to access Plex through a domain `plex.example.com` (I'm assuming that domain has been anonymized in the log). If Plex is being reverse proxied, you'll need to make sure that the timeouts are set high enough for every service inline with the request (reverse proxy, cache, CDN, etc.).

**Comment by bigdork** [comment]
> Does the script fail on the same collection every time or is it random?
Random. But a good example of one that never completes, due to massive size, is:
```
  Action & Adventure:
    genres: [Action, Adventure, Action/Adventure]
    sort_title: -2 Action & Adventure
    summary: A collection of movies from the Action and Adventure genres
    collection_order: alpha
```

> I've only really tested this on Python 3.7+, looks like this might be using Python 3.6. I think we've had this error before and it ended up being a dependency issue. Do you mind making sure the dependencies are up-to-date with something like pip install --upgrade -r requirements.txt?
```
$ pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyYAML==5.1.2 in /home/user/.local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (5.1.2)
Requirement already satisfied: PlexAPI==4.1.2 in /home/user/.local/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (4.1.2)
Requirement already satisfied: tmdbv3api==1.6.2 in /home/user/.local/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (1.6.2)
Requirement already satisfied: trakt.py==4.2.0 in /home/user/.local/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (4.2.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 8)) (4.4.2)
Requirement already satisfied: requests>=2.4.2 in /home/user/.local/lib/python3.6/site-packages (from -r requirements.txt (line 9)) (2.24.0)
Requirement already satisfied: ruamel.yaml in /home/user/.local/lib/python3.6/site-packages (from -r requirements.txt (line 10)) (0.16.12)
Requirement already satisfied: six<2.0.0,>=1.10.0 in /home/user/.local/lib/python3.6/site-packages (from trakt.py==4.2.0->-r requirements.txt (line 6)) (1.15.0)
Requirement already satisfied: arrow<1.0.0,>=0.10.0 in /home/user/.local/lib/python3.6/site-packages (from trakt.py==4.2.0->-r requirements.txt (line 6)) (0.17.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/user/.local/lib/python3.6/site-packages (from requests>=2.4.2->-r requirements.txt (line 9)) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.4.2->-r requirements.txt (line 9)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/user/.local/lib/python3.6/site-packages (from requests>=2.4.2->-r requirements.txt (line 9)) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/user/.local/lib/python3.6/site-packages (from requests>=2.4.2->-r requirements.txt (line 9)) (1.25.11)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /home/user/.local/lib/python3.6/site-packages (from ruamel.yaml->-r requirements.txt (line 10)) (0.2.2)
Requirement already satisfied: python-dateutil>=2.7.0 in /home/user/.local/lib/python3.6/site-packages (from arrow<1.0.0,>=0.10.0->trakt.py==4.2.0->-r requirements.txt (line 6)) (2.8.1)
```

> How long do Plex searches usually take to return in the web UI? The timeout default is 30 seconds, but it looks like it can be adjusted: https://github.com/pkkid/python-plexapi/blob/master/docs/configuration.rst . If Plex's web UI returns searches in <30 seconds, the problem probably may not be related to library size unless either machine is way underpowered.
Typical searches are no issue, although on occasion I guess I get a "Unable to load item" for no discernible reason. It has ALWAYS been that way, so I just assumed normal behavior.  I'll check out that link, but the machine is not underpowered. Hetzner Dedi server with plenty of CPU/RAM, Plex is in a docker and metadata is on local NVME. The media itself is hosted on GDrive and presented to Plex via unionfs.

> Lastly, it looks like the script is trying to access Plex through a domain plex.example.com (I'm assuming that domain has been anonymized in the log). If Plex is being reverse proxied, you'll need to make sure that the timeouts are set high enough for every service inline with the request (reverse proxy, cache, CDN, etc.).
Yes, I anonymized the output, but I have pointed to the public name. I am reverse proxied, but, since I'm running in console on the same machine as the Plex docker, I will attempt to go direct. Hadn't considered the rproxy...

**Comment by burkasaurusrex** [comment]
It looks like the request that is timing out it is one of the simplest requests / should be the fastest (it's failing on pulling an individual movie by its plex ID).

Any luck with testing it directly? If not, I'd probably try extending the timeout too by setting an `env` of `PLEXAPI_PLEXAPI_TIMEOUT` to 60 or 120. Or could try setting via the config file mentioned in the link above.

**Comment by mza921** [comment]
The timeout to the Plex server is currently hard-coded to 60 seconds. A config option can be added to increase this.

**Comment by bigdork** [comment]
I created the file ~/.config/plexapi/config.ini with `timeout = 60` and the scripts are churning through! I'll have these 25K movies wrangled soon enough!

**Comment by Tharic99** [comment]
@bigdork or @burkasaurusrex when you say you created the ~/.config/plexapi/config.ini file, is that located in the root of your server itself?

I ask because I'm on an unraid server and I created the file in that root a few days ago, but today after a reboot, the file was gone. So I had to create it again. Seemed odd to me.

**Comment by bigdork** [comment]
Just seeing this. 

I'm unfamiliar with Unraid, but on Linux ~/.config/ is the .config directory in the user home. ~ equates to /home/username/ of the current user that is utilizing plexapi - so the actual path on Linux is /home/username/.config/plexapi/config.ini

Salt-to-taste for Unraid.

**Comment by chiggerz** [comment]
> Just seeing this.
> 
> I'm unfamiliar with Unraid, but on Linux ~/.config/ is the .config directory in the user home. ~ equates to /home/username/ of the current user that is utilizing plexapi - so the actual path on Linux is /home/username/.config/plexapi/config.ini
> 
> Salt-to-taste for Unraid.

hey man, it looks like we have an exact setup and i'm having same issue with this like you were.  Could I ask you share the content of the file you created and where you placed in? Are you using CloudCMD to access? im struggling to find this? Help would be much appreciated, ive come to this due to not being able to create dynamic libraries, so would be awesome to get this working. 

thanks in advance
