### ISSUE TITLE
TMDB Directors?

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#75]
I'm interested in syncing the movies a director has made to a collection and add missing movies to Radarr.
Any way to query TMDB directors, similar to tmdb_actor?

**Comment by meisnate12** [comment]
probably ill look into it for my next set of enhancements

**Comment by meisnate12** [comment]
actually it was easy it will be in the next release

**Comment by bigdork** [comment]
@meisnate12 Not all heroes wear capes.

**Comment by meisnate12** [comment]
I'm also adding `tmdb_writer` and am considering adding `tmdb_people` which when given a persons TMDb ID it will add everything they've acted, directed, or written. Would that be useful? At the moment you can accomplish this by setting `tmdb_actor`, `tmdb_director`, and `tmdb_writer` all as the same TMDb person ID.

**Comment by bigdork** [comment]
I currently don't have a use case for that, in fact I'm actively avoiding that scenario, but I definitely could see people using that for their Plex setups and it would be a nice rounding out of this feature.  In fact, if you're a completionist, I believe there's also "sound" and "production" roles that people might find useful too?

**Comment by meisnate12** [comment]
I choose not to do do producers mainly because there's not a field in plex for them but it's possible

**Comment by meisnate12** [comment]
if the 2.4.0+ adds what you were looking for lets close this

**Comment by bigdork** [comment]
@meisnate12 

Version 2.4.6 
`tmdb_director:` does not appear to work.

Config:
```
  Director Steven Spielberg:
    tmdb_director: 488
```
Output:
```
| Updating collection: Director Steven Spielberg...
| Sync Mode: append
Traceback (most recent call last):
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 830, in <module>
    update_from_config(config_path, plex, True, args.no_meta, args.no_images)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_auto_collections.py", line 461, in update_from_config
    missing, map = add_to_collection(config_path, plex, m, v, c, map, filters)
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 166, in add_to_collection
    movies = search_plex()
  File "/opt/scripts/Plex-Auto-Collections/app/plex_tools.py", line 134, in search_plex
    search_list = attr_pair[1]
IndexError: list index out of range
```

**Comment by meisnate12** [comment]
there should be the fix for this on my branch as well

**Comment by bigdork** [comment]
Branch appears working - Thank you!

```
| Updating collection: Director Steven Spielberg...
| Sync Mode: append
| Processing Plex Search: director(Steven Spielberg)
| Director Steven Spielberg Collection | = | 1941
| Director Steven Spielberg Collection | = | A.I. Artificial Intelligence
| Director Steven Spielberg Collection | = | The Adventures of Tintin
| Director Steven Spielberg Collection | = | Always
| Director Steven Spielberg Collection | = | Amblin'
| Director Steven Spielberg Collection | = | Amistad
| Director Steven Spielberg Collection | = | The BFG
| Director Steven Spielberg Collection | = | Bridge of Spies
| Director Steven Spielberg Collection | = | Catch Me If You Can
...
```

**Comment by meisnate12** [comment]
this can be closed
