### ISSUE TITLE
Bug: Only add 100 first result of an IMDB list

### ISSUE THREAD

**Issue by jalarab** [mza921/Plex-Auto-Collections#87]
I have script V. 2.4.1 last PMS.
When I try to use the script for a large IMDB list like https://www.imdb.com/list/ls023216066/, the collection were populated only with the first 100 items of the list (first page).

**Comment by jalarab** [comment]
I don't understand. This list https://www.imdb.com/list/ls023764240/ was complitely matched 471 items

**Comment by meisnate12** [comment]
im not sure whats going on with the other one but im going to look into it now

**Comment by meisnate12** [comment]
i found the error right now the max movies supported in an IMDB list is currently 999 due to a programming oversite our next release will have a fix for this

**Comment by meisnate12** [comment]
do you mind testing this for me? 

just open up imdb_tools.py and replace line 44 as seen below

What it looks like currently
```python
39    if "/search/" in imdb_url:
40        results = re.search('<span>\\d+-\\d+ of \\d+ titles.</span>', str(r.content))
41        total = 100 if results is None else re.findall('(\\d+)', results.group(0))[2]
42    else:
43        results = re.search('(?<=<div class="desc lister-total-num-results">).*?(?=</div>)', str(r.content))
44        total = 100 if results is None else re.search('.*?(\\d+)', results.group(0)).group(1)  #  <---Replace this line with the line below
```

change line 44 to
```python
44        total = 100 if results is None else re.search('.*?(\\d+)', results.group(0).replace(',', '')).group(1)
```

**Comment by jalarab** [comment]
same result, just the first 100

**Comment by meisnate12** [comment]
my tests show that this will fix it youll have to try the patch and see if that one works once its released

**Comment by jalarab** [comment]
In my case I have a list with 1435 movies and the script just add 118 to the collection. All movies are in my collection matched with the new agent.

**Comment by jalarab** [comment]
> my tests show that this will fix it youll have to try the patch and see if that one works once its released

I tested it and didn't solve the issue with the first 100 items of the list
